### ISSUE TITLE
v2.8.4 crashes for Outlook 2003

### ISSUE THREAD

**Issue by phw198** [phw198/OutlookGoogleCalendarSync#1059]
**OGCS Version**: v2.8.4.0  
**Edition**: Installed / Portable  
**Sync Direction**: Any

**Bug Description**  
OGCS crashes immediately when started on a system with Outlook 2003.

**Steps to Reproduce the Issue**  
1. Run OGCS
1. It crashes on instantiation

**Any other information**  
```
2020-08-16 16:16:37,891 DEBUG  9 OutlookGoogleCalendarSync.Forms.Main [196] -  List Calendar folders
2020-08-16 16:16:38,099 WARN  9 OutlookGoogleCalendarSync.Forms.Main [927] -  Outlook calendar selection changed to: Calendar (ID: 0000000099E5D537CEB2D74B8C7E116BFC60929E22810000)
2020-08-16 16:16:38,457 ERROR  9 OutlookGoogleCalendarSync.OGCSexception [64] -  System.NullReferenceException: Object reference not set to an instance of an object.
2020-08-16 16:16:38,459 ERROR  9 OutlookGoogleCalendarSync.OGCSexception [64] -  Code: 0x80004003;-2147467261
2020-08-16 16:16:38,460 ERROR  9 OutlookGoogleCalendarSync.OGCSexception [64] -     at OutlookGoogleCalendarSync.Extensions.OutlookColourPicker.AddCategoryColours() in C:\Users\Paul\Git\OutlookGoogleCalendarSync\src\OutlookGoogleCalendarSync\Extensions\ColourPicker.cs:line 38
   at OutlookGoogleCalendarSync.Extensions.OutlookColourPicker.AddColourItems() in C:\Users\Paul\Git\OutlookGoogleCalendarSync\src\OutlookGoogleCalendarSync\Extensions\ColourPicker.cs:line 22
   at OutlookGoogleCalendarSync.Forms.Main.updateGUIsettings() in C:\Users\Paul\Git\OutlookGoogleCalendarSync\src\OutlookGoogleCalendarSync\Forms\MainForm.cs:line 329
   at OutlookGoogleCalendarSync.Forms.Main..ctor(String startingTab) in C:\Users\Paul\Git\OutlookGoogleCalendarSync\src\OutlookGoogleCalendarSync\Forms\MainForm.cs:line 45
   at OutlookGoogleCalendarSync.Program.Main(String[] args) in C:\Users\Paul\Git\OutlookGoogleCalendarSync\src\OutlookGoogleCalendarSync\Program.cs:line 72
2020-08-16 16:16:38,464 FATAL  9 OutlookGoogleCalendarSync.Program [100] -  Application unexpectedly terminated!
```

**Comment by phw198** [comment]
:package: This should now be resolved with [hotfix v2.8.4.7.zip](https://github.com/phw198/OutlookGoogleCalendarSync/files/5081058/v2.8.4.7.zip) ([see instructions for applying](https://github.com/phw198/OutlookGoogleCalendarSync/wiki/Reporting-Problems#applying-a-hotfix) - it must be applied onto v2.8.4.0).

Please let me know how it goes.

**Comment by alaingheysens** [comment]
![2020-08-17_092235](https://user-images.githubusercontent.com/49584753/90401133-cfdbd780-e09d-11ea-837e-b1a65e1c94cb.jpg)
[OGcalsync (2.8.4.0).log](https://github.com/phw198/OutlookGoogleCalendarSync/files/5084454/OGcalsync.2.8.4.0.log)
[OGcalsync.log](https://github.com/phw198/OutlookGoogleCalendarSync/files/5084455/OGcalsync.log)

Dear Paul,
 
Thank you for your messages. I apologize for my late replies being on holidays.
The situation got a little bit worse, nothing seems to work anymore.
Included, the logs and printscreen of the crashreport after replacing the executable file.
Hoping you will find a solution sometimes.
Meanwhile I reverted to old 2.8.0.0 that functions except for the duplicate entrances.
 You asked me on August 8th how I added the birthdays in Google, they are added manually, not from my contacts.
Best regards,

**Comment by phw198** [comment]
So to be clear, you install version 2.8.4-alpha and then afterwards replaced the `C:\Users\<userid>\AppData\Local\OutlookGoogleCalendarSync\app-2.8.4-alpha\OutlookGoogleCalendarSync.exe` file with the hotfix posted above? 

I've just tested that and it works OK. Can you provide me the `OGcalsync.log` file after the crash on v2.8.4.7?

**Comment by cdenke** [comment]
Thanks a lot for the hotfix - yes, 2.8.4.7 solved the issue with the connection to Outlook 2003 (which I continue to use).
Before I saw the hotfix, I had tested 2.8.4 (0) with a new (empty) Google calendar; old error persisted.
With 2.8.4.7 exe, the (still empty) Google calendar was populated without an error being reported. 
I would assume this is sufficient proof of success or would you like the log file?
At the moment, no further update syncs were tested yet.
Thanks again for the efforts you put into the compatibility with legacy software
Christian

**Comment by phw198** [comment]
@cdenke Yes that sounds like this issue is resolved! I assume you have been able to use OGCS successfully over the last week on 2003?

@alaingheysens Any success getting this hotfix to run yourself? Would be nice to get a fix for #1051 into the next release of OGCS...
