### ISSUE TITLE
Multi-calendar Sync / "Profiles" :: Early Adopters Required

### ISSUE THREAD

**Issue by phw198** [phw198/OutlookGoogleCalendarSync#1307]
The long wait for being able to sync more than one calendar (without running mutliple instances of OGCS) is over!

:point_right: Before jumping in, please ensure you [understand what is required of an Early Adopter](https://github.com/phw198/OutlookGoogleCalendarSync/wiki/Multi-calendar-sync%21-AKA-%22Profiles%22) and how to get involved.
:point_right: Please subscribe to this issue, in order you are notified of new releases etc

### Releases
:package: [v2.9.2.5.zip](https://github.com/phw198/OutlookGoogleCalendarSync/files/7577235/v2.9.2.5.zip) | 21-Nov-2021

<details>
<summary><b>Previous Releases</b></summary>

:package: [v2.9.2.1.zip](https://github.com/phw198/OutlookGoogleCalendarSync/files/7534285/v2.9.2.1.zip) | 14-Nov-2021
:package: [v2.9.1.11.zip](https://github.com/phw198/OutlookGoogleCalendarSync/files/7429903/v2.9.1.11.zip) | 28-Oct-2021
:package: [v2.9.1.10.zip](https://github.com/phw198/OutlookGoogleCalendarSync/files/7421474/v2.9.1.10.zip) | 26-Oct-2021
:package: [v2.9.1.9.zip](https://github.com/phw198/OutlookGoogleCalendarSync/files/7406244/v2.9.1.9.zip) | 24-Oct-2021
:package: [v2.9.1.6.zip](https://github.com/phw198/OutlookGoogleCalendarSync/files/7318269/v2.9.1.6.zip) | 10-Oct-2021
:package: [v2.9.1.5.zip](https://github.com/phw198/OutlookGoogleCalendarSync/files/7289778/v2.9.1.5.zip) | 06-Oct-2021
:package: [v2.9.1.4.zip](https://github.com/phw198/OutlookGoogleCalendarSync/files/7268741/v2.9.1.4.zip)  | 01-Oct-2021
</details>

**Comment by ghnogueira** [comment]
I'm not able to have the commitment to help, but thanks and good luck to everyone involved :)

**Comment by billlanding** [comment]
I downloaded and installed 2.9.1.4 and got two profiles set up. if I press Sync to manually sync either profile they seem to sync just fine but I get errors when it syncs on its schedule (2-hour frequency). 
[OGcalsync.log](https://github.com/phw198/OutlookGoogleCalendarSync/files/7305268/OGcalsync.log)
Now I see that you've posted 2.9.1.5. I will try installing this and see what happens.

**Comment by SVNKoch** [comment]
I just got the version and will use it and report if there are errors coming up ;)

PS now with the profiles I think the settings need to be restructered such that you always see (and be able to switch) the profile no matter the selected settings tab.
As the Application Behaviour isn't affected by the profile it should be its seperate thing. I just made a quick mockup:
![grafik](https://user-images.githubusercontent.com/39488412/136476842-3a96a67a-4fa6-4518-a392-02b37ba89fa5.png)

PPS: this month is #Hacktoberfest, maybe you want to tag your repo for this as well ;D

**Comment by SVNKoch** [comment]
Sync Tab should have two buttons Sync this Profile and sync all Profiles (ofc both with Full sync capability when pressing shift)

**Comment by hildetand** [comment]
Would be great if all profiles could be synced at same time

**Comment by wir3z** [comment]
I'm noticing some issues when multiple exange calendars are used.  The profiles seem to blend with the source and destinations getting corrupted and mixed.

For example:
Profile1:  default outlook account
Profile2:  alternate outlook account
Profile3:  shared calendar (shared mailbox)

The source and destinations of profile 1 and 2 get messed up, sometimes swapped, etc.

**Comment by phw198** [comment]
@SVNKoch Thanks - yes I agree the GUI needed updating, having got the backend code mostly done. You should see your proposal in v2.9.1.6 :slightly_smiling_face:

**Comment by phw198** [comment]
> Would be great if all profiles could be synced at same time

@hildetand I can make them sync sequentially (which is what @SVNKoch is [also suggesting](https://github.com/phw198/OutlookGoogleCalendarSync/issues/1307#issuecomment-938234688)), but not at the same time.

@wir3z I'd need to know the exact order of events leading up to this as well as your logfile to investigate this further. Please apply v2.9.1.6 first though and wait for the issue to reoccur.

**Comment by billlanding** [comment]
Just updated to 2.9.1.6 and got this error, regardless of which profile I tried to manually sync: 

Problem encountered during synchronisation.
Object reference not set to an instance of an object.
[OGcalsync.log](https://github.com/phw198/OutlookGoogleCalendarSync/files/7318235/OGcalsync.log)

**Comment by phw198** [comment]
@billlanding Oops, sorry about that! I've re-released v2.9.1.6...

**Comment by billlanding** [comment]
Installed the latest v2.9.1.6. Manual sync works on both profiles with no reported errors. I don't see the option requested by SVN Koch which you implied had been implemented, "Sync Tab should have two buttons Sync this Profile and sync all Profiles"

I will wait to see if an automatic sync will sync both profiles.

**Comment by wir3z** [comment]
> @wir3z I'd need to know the exact order of events leading up to this as well as your logfile to investigate this further. Please apply v2.9.1.6 first though and wait for the issue to reoccur.

Seems to be a two-fold thing.   
First:
- When I select the outlook tab, it starts to scan for calendars.  When I do the pull-down for "alternate mailbox", the list gains one an additional duplicate email address each time the calendar scan occurs.  For example, it starts with:
- email1@email.com
- email2@email.com
Next refresh, it looks like this:
- email1@email.com
- email1@email.com
- email2@email.com
- email2@email.com

When you select multiple alternate email profiles, and you restart OGCS, it always defaults to the first email in the list, so if the second profile was email2@email.com, it will show as email1@email.com.  As long as it was saved properly, it seems to sync properly.


The corrupted issue I was seeing was one profile was trying to delete an entry from the google calendar, and it would error 404 and stop syncing.  If you click "resume" then the sync would replicate events across all the profiles.  Seems to be an issue handling the error trap.  I'll see if I can get an log when this happens.

**Comment by billlanding** [comment]
Still getting sync errors when a scheduled sync happens while the laptop is asleep. Popup screen asks if I want to keep trying: Yes or No. Hitting yes generates error: 

>Updated event failed to save.
Not Found [404=NotFound]

I assume this error stops the current sync attempt, and presumably all future sync attempts, until I happen to notice the popup screen and take some action. Brute force solution might be to remove OGCS from Startup, set frequency to 24 hours or more, and run manually when I think of it. Hopefully you can think of a better solution.

[OGcalsync.log](https://github.com/phw198/OutlookGoogleCalendarSync/files/7323021/OGcalsync.log)

**Comment by wir3z** [comment]
Here is a log for the multiple profile issue.  When I restart OGCS, it has a popup saying the calendar isn't available anymore, so it's defaulting to the default "calendar".

[OGcalsync-calendar no longer available.log](https://github.com/phw198/OutlookGoogleCalendarSync/files/7323566/OGcalsync-calendar.no.longer.available.log)

**Comment by wir3z** [comment]
Here is a log where I'm getting a 404 error for orphaned items.  If I check the google calendar, the item is there.  If I manually sync, it succeeds, the automatic sync fails.
```
Checking for orphaned Google items

Reclaiming Outlook calendar entries
Reclaimed: 2021-10-25 12:30 PM "Mammogram/Ultrasound "

Failure processing Outlook item:-
2021-10-25 12:30 PM "Mammogram/Ultrasound "

Unable to reclaim orphan calendar entries in Outlook calendar.

Not Found [404=NotFound]

Sync aborted after 1 failed attempts!
Another sync has been scheduled to automatically run in 15 minutes time
```
[OGcalsync-missing orphaned 404.log](https://github.com/phw198/OutlookGoogleCalendarSync/files/7323586/OGcalsync-missing.orphaned.404.log)

**Comment by wir3z** [comment]
I found something else.  When I have a main email profile, alternate email profile and a shared profile, everything works fine with a manual sync.

When I let it sync automatically (currently 15 minutes),  the alternate and shared profiles will start creating duplicate events.  If I manually sync, then they get deleted.  Let it auto-sync, and they are duplicated again.  I managed to get 58 reminders of "thanksgiving" this morning,  :)

I closed OGCS, and re-opened it, and then I get an error about the alternate and/or shared mailbox is not accessible.  Start the application again, and then it's fine again.  I've attached a log of this occurring.

I have OGCS running on a virtual machine that never sleeps.

[OGcalsync_auto_duplicates.log](https://github.com/phw198/OutlookGoogleCalendarSync/files/7323945/OGcalsync_auto_duplicates.log)

**Comment by billlanding** [comment]
Turned on PC for today.
OGCS runs from Startup.
No apps open; nothing else running.
1st profile (KTB, the shared Google calendar) starts to sync.
Errors "Failure processing Outlook item". Sync stops.
Asks if I want to try again.
Yes; sync re-starts but yields the same error but on different Outlook calendar items.
Asks if I want to try again.
Yes; sync re-starts but yields the same error but on different Outlook calendar items.
Asks if I want to try again.
No. Log file attached.
[OGcalsync.log](https://github.com/phw198/OutlookGoogleCalendarSync/files/7332666/OGcalsync.log)

**Comment by wir3z** [comment]
> Turned on PC for today. OGCS runs from Startup. No apps open; nothing else running. 1st profile (KTB, the shared Google calendar) starts to sync. Errors "Failure processing Outlook item". Sync stops. Asks if I want to try again. Yes; sync re-starts but yields the same error but on different Outlook calendar items. Asks if I want to try again. Yes; sync re-starts but yields the same error but on different Outlook calendar items. Asks if I want to try again. No. Log file attached. [OGcalsync.log](https://github.com/phw198/OutlookGoogleCalendarSync/files/7332666/OGcalsync.log)

For me when it errors during an auto-sync, it continues to error on multiple items.  If I manually sync using the icon on the taskbar, it full succeeds.

A 'nice to have' would be the ability for it to ignore and resume if there was an error.  If it errors on the first mailbox, there is no longer any syncs on any items on any mailbox until you acknowledge the failure.

**Comment by wir3z** [comment]
I found something with the repetitive task creation.  This is happening even when sync is disabled (I had it set to sync every 15 minutes, but then turned off auto-sync).

When I checked today, I had 1600 erroneous duplicates.  I've just tried setting the sync interval to "0" to see if it is fine with pure manual syncs.  If I run a manual sync, it identifies those duplicates and then proceeds to delete them again.

**Comment by phw198** [comment]
Thanks for all the updates. Although I've not been able to investigate the 404 errors yet, I've just released v2.9.1.9 which has a bunch of bug fixes around properly selecting the correct profile when switching - so with any luck it may have fixed the 404s.

Please give [v2.9.1.9 a whirl](https://github.com/phw198/OutlookGoogleCalendarSync/files/7406244/v2.9.1.9.zip) and continue to update on issues encountered.

**Comment by wir3z** [comment]
Couple of notes:
1)  I'm getting some sync issues with this version (happens on all profiles)  As soon as the sync should end, I get a 
```
Microsoft .NET framework Unhandled exception window, with this comment "Object reference not set to an instance of an object".  Excerpt from log shows the same:
2021-10-24 16:10:08,111 WARN  1 OutlookGoogleCalendarSync.OutlookOgcs.Categories [127] -  Failed getting non-default mailbox categories. Object reference not set to an instance of an object.
2021-10-24 16:10:08,112 DEBUG  1 OutlookGoogleCalendarSync.OutlookOgcs.Categories [128] -  Reverting to default mailbox categories.
```
2)  When you switch profiles, you need to be on the Outlook tab, or the content doesn't change.  If I'm on the Google or Sync Options tabs, the information displayed is still from the previous profile.

3)  I think the issue with using multiple alternate mailboxes is Outlook calls them all "Calendar" so there is an overlap conflict with two profiles, both using "Calendar".

**Comment by wir3z** [comment]
I haven't seen the 404 errors in a while, but they have come back.  I've attached a log when they are happening.  It looks like its on one Outlook profile, but looking at another profile for the google calendar.  In the log case, it's processing a profile called "VDI", but the 404 errors are for events on the "SharedCalendar" profile.
[OGcalsync.log](https://github.com/phw198/OutlookGoogleCalendarSync/files/7406399/OGcalsync.log)

**Comment by wir3z** [comment]
Here is what the dialog error pop-up is saying.  Might be helpful to debug:


See the end of this message for details on invoking 
just-in-time (JIT) debugging instead of this dialog box.
```
************** Exception Text **************
System.NullReferenceException: Object reference not set to an instance of an object.
   at OutlookGoogleCalendarSync.Settings.Profile.GetType(Object settingsStore) in C:\Users\Paul\Git\OutlookGoogleCalendarSync\src\OutlookGoogleCalendarSync\SettingsStore\Settings.cs:line 425
   at OutlookGoogleCalendarSync.Settings.Profile.Name(Object settingsStore) in C:\Users\Paul\Git\OutlookGoogleCalendarSync\src\OutlookGoogleCalendarSync\SettingsStore\Settings.cs:line 434
   at OutlookGoogleCalendarSync.Sync.Engine.set_ActiveProfile(Object value) in C:\Users\Paul\Git\OutlookGoogleCalendarSync\src\OutlookGoogleCalendarSync\Sync\Engine.cs:line 65
   at OutlookGoogleCalendarSync.Sync.Engine.Calendar.StartSync(Boolean updateSyncSchedule) in C:\Users\Paul\Git\OutlookGoogleCalendarSync\src\OutlookGoogleCalendarSync\Sync\Calendar.cs:line 0
   at OutlookGoogleCalendarSync.Sync.Engine.Start(Boolean updateSyncSchedule) in C:\Users\Paul\Git\OutlookGoogleCalendarSync\src\OutlookGoogleCalendarSync\Sync\Engine.cs:line 184
   at OutlookGoogleCalendarSync.Sync.Engine.QueueTimer_Tick(Object sender, EventArgs e) in C:\Users\Paul\Git\OutlookGoogleCalendarSync\src\OutlookGoogleCalendarSync\Sync\Engine.cs:line 52
   at System.Windows.Forms.Timer.OnTick(EventArgs e)
   at System.Windows.Forms.Timer.TimerNativeWindow.WndProc(Message& m)
   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)
```

**Comment by Kant-Lavar** [comment]
Updated to the new version this morning, still getting the same 404 errors as in #1326 

[OGcalsync.log](https://github.com/phw198/OutlookGoogleCalendarSync/files/7410226/OGcalsync.log)

Also getting similar exception errors as the above users.

[2-9-1-9 exception errors.txt](https://github.com/phw198/OutlookGoogleCalendarSync/files/7410459/2-9-1-9.exception.errors.txt)

**Comment by SVNKoch** [comment]
I'm getting the same 404

**Comment by wir3z** [comment]
One thing I noticed is if you look at the sync window, and this fails to work, the profile listed at the top does not match the profile that is being acted on in the body.

The top will say "Profile 1, Last Sync, Next Sync" but when it starts to process, the body will be saying "Profile 2" and then it starts with the 404 errors since events from Profile 2 legitimately do not exist in Profile 1.

**Comment by phw198** [comment]
The `Object reference not set to an instance of an object.` should now be fixed in v2.9.1.10.

I've got a handle on what's causing the 404s, but may take me a little while to fix it...

> When you switch profiles, you need to be on the Outlook tab, or the content doesn't change.

@wir3z I can't reproduce this?

**Comment by wir3z** [comment]
> > When you switch profiles, you need to be on the Outlook tab, or the content doesn't change.
> 
> @wir3z I can't reproduce this?

I just tried in the latest version, and I see it changes, it just isn't instantaneous.  IE:  If I click a new profile, it may take 5 seconds before it refreshes and the tab data reflects the new profile.  It does change though.

**Comment by phw198** [comment]
Spent some time on the 404 issue - please load up [v2.9.1.11](https://github.com/phw198/OutlookGoogleCalendarSync/files/7429903/v2.9.1.11.zip) to see if that resolves it.

@wir3z I think that might be because it's taking 5 seconds to enumerate the Outlook calendar folders you have? I guess I could see if I can move the load of the Outlook settings tab to the end, so the other tabs update quicker first...

**Comment by sirloinofbeef** [comment]
When running a test on 2.9.1.11 I get "Unable to perform test" "Could not open the item. Try again."
Am able to run tests and sync single calendar fine using 2.9.1.0.

```
2021-10-28 19:50:53,262 ERROR  1 OutlookGoogleCalendarSync.Settings [463] -  Unknown profile being referenced.
2021-10-28 19:50:53,347 INFO  1 OutlookGoogleCalendarSync.OutlookOgcs.ExplorerWatcher [20] -  Setting up Explorer event watchers.
2021-10-28 19:50:53,350 DEBUG  1 OutlookGoogleCalendarSync.OutlookOgcs.ExplorerWatcher [21] -  Watcher needed for 0 existing explorers.
2021-10-28 19:50:53,408 WARN  1 OutlookGoogleCalendarSync.OGCSexception [1276] -  Profile 'Default', calendar ID 00000000BACDC3A9BE16364FBF93055EEFD5398C0100DD4243AA084C554D80D88950F2E99AD500000000010D0000
2021-10-28 19:50:53,411 ERROR  1 OutlookGoogleCalendarSync.OGCSexception [28] -  System.Runtime.InteropServices.COMException: Could not open the item. Try again.
2021-10-28 19:50:53,413 ERROR  1 OutlookGoogleCalendarSync.OGCSexception [21] -  Code: 0x80020009,-2147352567; Location: GetFolderFromID() in <Unknown File>
```

**Comment by wir3z** [comment]
This version seems to have fixed almost all issues I was seeing.  Profiles now automatically sync properly without the duplicates as I seen before.  Some notes:
1)  When switching profiles, you are correct, it's the enumeration.  If I was on the Outlook tab, you grey settings with a yellow indicator that it's busy.  On the google or sync tab, there is no indicator.  If I wait for the time that it would enumerate, then it populates.  Maybe some sort of "busy" indicator on those tabs while it's enumerating?
2)  Still doesn't support multiple alternate calendars.  But is working perfectly on a default, a shared and an alternate (so 3 simultaneously).
3)  On the sync options, if I select or deselect "attendees" that checkbox seems to be changing multiple profiles at the same time.  IE:  I changed it for the shared calendar, and when I check the alternate calendar, the setting mirrored.  

Looking really good though!

**Comment by wir3z** [comment]
I went in to swap the google shared calendar destination, and managed to trip that "alternate calendar could not be found".  I've attached the log for the instance
[OGcalsync.log](https://github.com/phw198/OutlookGoogleCalendarSync/files/7435854/OGcalsync.log)
.

**Comment by billlanding** [comment]
Version 2.9.1.11 is auto-syncing both of my profiles with no obvious errors.
[OGcalsync.log](https://github.com/phw198/OutlookGoogleCalendarSync/files/7468803/OGcalsync.log)

**Comment by Megacheezy** [comment]
version 2.9.1.11 is syncing all profiles without issues so far.
initially it somehow kept resyncing (and schedulign them, as shown in next scheduled sync) every 30 seconds even though its set to hourly  resync.
a restart and manual sync seems to have fixed as i see the next scheduled now indeed 1 hour from now. 

edit, just had a sync happen ,even though next scheduled is still 45 minutes away. and only synched one profle as far as

**Comment by phw198** [comment]
> I went in to swap the google shared calendar destination, and managed to trip that "alternate calendar could not be found". I've attached the log for the instance [OGcalsync.log](https://github.com/phw198/OutlookGoogleCalendarSync/files/7435854/OGcalsync.log) .

@wir3z I've opened #1335 to cover this, if you could apply the patch there to troubleshoot further.

**Comment by wir3z** [comment]
Using 2.9.1.12, and I seem to get a failure loading the shared calendar profile during a scheduled sync after a PC restart.  I've attached a log with the details.  I will check the PC, the GUI will indicate a failure.  If you select "retry" it will fail forever.  If you abort, then the rest of the automatic syncs will continue, and it will heal itself.  The scheduled profiles will then sync without issues.

[OGcalsync.log](https://github.com/phw198/OutlookGoogleCalendarSync/files/7521213/OGcalsync.log)

**Comment by wir3z** [comment]
I see it's prompting for the new alpha update when I run (2.9.2.0) and I thought it mentioned profiles in the release note prompt, but they aren't there when its installed.  Just checking.  :)

**Comment by phw198** [comment]
@wir3z No, I've held off of releasing Profiles just yet - aiming for v2.9.3! Meanwhile, I've just posted v2.9.2.1 with the Profiles in it to continue testing...

**Comment by wir3z** [comment]
Sorry, I misread it before.  If I ACTUALLY read the notes that popped up, it clearly states it's coming in 2.9.3.  :)

Thanks for all your hard work on this.

**Comment by sirloinofbeef** [comment]
2.9.2.1 fixed my problem. Now syncing 3 calendars.
Awesome work.

**Comment by wir3z** [comment]
Occasionally I'm getting a hang-up on the sharedcalendar sync.  I've attached a log (it was only set to "warn" level, so I've set it back to debug to try to catch it again).

When I log into the PC, the GUI is displaying a red message of "The operation failed.  The messaging interfaces have returned an unknown error. If the problem persists, restart Outlook.".  If you click "retry" it just perpetually fails.  If I hit cancel, then 
 it proceeds to resync all calendars without issue, and works again.

Also noted, is it seems to spawn Outlook at the same time.  I normally keep outlook closed, but it will be open during this failure.
[OGcalsync.log](https://github.com/phw198/OutlookGoogleCalendarSync/files/7555976/OGcalsync.log)

**Comment by Treader** [comment]
Version: 2.9.2.1

I have 4 different sync profiles setup: 
1) Google main calendar -> Outlook work calendar `FROM GMAIL` `36ED7`
Profile: DBW
2) Google shared calendar -> Outlook work calendar `FROM GMAIL` `36ED7`
Profile: Shared with Don
3) Outlook work calendar `36ED7` -> Google "Synced with Outlook" calendar `(amf)` 
Profile: Sync FROM AMF outlook
4) Outlook personal calendar `5593BF` -> Google "Synced from Outlook" calendar. `(sell919)`
Profile: Sync FROM sell919 outlook

The main goal is to have my 2 google cals put their data to my work calendar and then have both my 365 accounts sync back to a synced with outlook. They should only grab the categories tagged "Sync with Gmail" in outlook. However doing the selection of label to include only checking "Sync with Gmail" would sometimes save and sometimes not. Dumping in a ton of data to gmail calendar. When i would look at the settings XML it showed my changes, but the program didn't seem to care. Persisted even on a restart.

I have Word Obfuscate enabled on each profile. for 1,2 it does all lines to "FROM GMAIL" this works great. 
for 3 I have it add "(amf) subject text here" and 4 has "(sell919) subject text here" 

Somehow the sync pushed all my data to sell919 calendar when it's not supposed to even sync that direction. ONLY to google.

And the AMF profile i see it rename the "(amf) move to 18" calendar event (which was correct) to "(sell919) move to 18" 

I would also get duplicates on my work calendar from the 2 gmail sync's. So a day that only had 1 event would have 2. 

I cleared out all the bad calendar events this morning from my calendars. I'll email you the private gist link with the log files.

**Comment by Treader** [comment]
Follow up, I noticed when I saw an auto run that the profile at the top of the sync screen didn't change. It was showing profile my shared calendar profile (that direction is only gmail shared -> work calendar) but what ran in the white text box automatically was the profile "Sync FROM sell919" (which is personal 365 calendar -> gmail Synced with Outlook calendar only direction) and the content from my shared calendar on gmail was then pushed to my personal 365 account calendar with the "(sell919) *" title changes. The personal sell919 calendar should never have anything pushed to it based on my settings in the app and XML. Hope that helps.

**Comment by wir3z** [comment]
> Occasionally I'm getting a hang-up on the sharedcalendar sync. I've attached a log (it was only set to "warn" level, so I've set it back to debug to try to catch it again).
> 
> When I log into the PC, the GUI is displaying a red message of "The operation failed. The messaging interfaces have returned an unknown error. If the problem persists, restart Outlook.". If you click "retry" it just perpetually fails. If I hit cancel, then it proceeds to resync all calendars without issue, and works again.
> 
> Also noted, is it seems to spawn Outlook at the same time. I normally keep outlook closed, but it will be open during this failure. [OGcalsync.log](https://github.com/phw198/OutlookGoogleCalendarSync/files/7555976/OGcalsync.log)

I managed to catch this issue again.  The log shows that the sync got hung on this error yesterday around 1PM.  When I checked this morning (8AM), Outlook was open, the GUI had a message saying "sync failed, do you wish to retry".  If I select "yes", that last error in the log repeats for every "yes" press.  If I select "no", then it proceeds to sync the rest of the calendars.

[OGcalsync.log](https://github.com/phw198/OutlookGoogleCalendarSync/files/7571416/OGcalsync.log)

**Comment by phw198** [comment]
@Treader 
> I would also get duplicates on my work calendar from the 2 gmail sync's. So a day that only had 1 event would have 2.

I think this is a configuration problem - you have profile 1) and 2) to _exclude_ Outlook categories, including exclusion of the `<No category assigned>`. Both these profiles are also not setting a category in Outlook, so each sync OGCS thinks it has to resync everything again on each sync.

> They [profiles 1 and 2] should only grab the categories tagged "Sync with Gmail" in outlook.

I only see one reference to this category, which is your DBW profile and is marked for _exclusion_ again.
```
2021-11-18 00:12:53,571 INFO  1 OutlookGoogleCalendarSync.SettingsStore.Calendar [240] -    Category Filter: Exclude
2021-11-18 00:12:53,571 INFO  1 OutlookGoogleCalendarSync.SettingsStore.Calendar [241] -    Categories: <No category assigned>,405 Birkby,Blue category,Green category,Orange category,Purple category,Red category,Sync with Gmail
```
....ah we have a bug here! When switching between profiles where one is include categories, and the other exclude, it inverts the selection and messes it up.

I also note you are minimising OGCS to the notification tray and I think this may have been causing problems properly switching profile too.

**Comment by phw198** [comment]
@wir3z v2.9.2.5 should now cope with your "The operation failed. The messaging interfaces have returned an unknown error. If the problem persists, restart Outlook." problem.

**Comment by wir3z** [comment]
> @wir3z v2.9.2.5 should now cope with your "The operation failed. The messaging interfaces have returned an unknown error. If the problem persists, restart Outlook." problem.

Loaded and testing.  Fingers crossed!

**Comment by wir3z** [comment]
So far so good.  It's been flawless on the 2.9.2.5

**Comment by wir3z** [comment]
Still working perfectly!  Only thing I see after a period of time I will see Outlook open/minimized to the taskbar.  This PC isn't actually used for anything, so no person ever opens Outlook.  Not sure if it's a Microsoft thing or what, and it happens about after a week.  I'll close it and then about a week later it will be open/minimized.

**Comment by wir3z** [comment]
Might have jinxed this.  Seems to have stopped sync'ing on Dec 4.  Logging stopped at that time, with this being the final entry:
2021-12-04 07:02:05,020 WARN  1 OutlookGoogleCalendarSync.OutlookOgcs.Calendar [987] -  Attachment failed - Outlook is running without GUI for programmatic access.

I had mentioned outlook keep auto-opening.  Does it need to be open for OGCS to properly work?  Doesn't matter to me either way, just checking.

**Comment by phw198** [comment]
That log entry is expected if Outlook is not open, but it should then proceed to connect to Outlook and sync. 

What was the status of OGCS? Was the application still open and useable or had it frozen or crashed? I wonder if there could be a memory leak or something...

Have you got it working again now?

**Comment by wir3z** [comment]
Ok, that's for clarifying that.

It was non-responsive.  Silly me didn't check the resource manager, and just rebooted the PC, so I don't know if it was a memory leak.  I'll keep my eye on it.

Once the PC came back, it started running fine again.

**Comment by wir3z** [comment]
So it seems it ran for about 5 hours and hung again.  OGCS was fine memory wise, but the Outlook Program Access was pinning CPU usage.  I couldn't right click / kill on the taskbar, and once I killed Outlook in the task manager, it healed and started up again.

I switch to full debug logging, and will attach a log if it happens again.

**Comment by wir3z** [comment]
Something odd going on.  Not sure if it's just a "me" issue.   I've attached a log, and it seems to run for a bit, and then just hang in the sync.  No syncs or log entries are recorded, and when I open the GUI, it shows the sync date/times in the past with it stuck in syncing.  It shows "stop sync" but the program is 100% non-responsive.   I cannot stop or close the application.  The only cure is to open task manager and kill the Outlook access.

If you look at the attached log:
2021-12-14 14:13:31 - last entry before it died
2021-12-14 17:41:47 - opened the GUI
2021-12-14 17:45:54 -> on - I terminated the Outlook process with task scheduler.

At this point I could re-sync and it started again.

[OGcalsync.log](https://github.com/phw198/OutlookGoogleCalendarSync/files/7715669/OGcalsync.log)

**Comment by wir3z** [comment]
Ok, this seems to be a MS problem.  I ended up doing the "online repair" of office, and it's been flawless for the past 3 days again.  Previously, it would only run for 4-6 hours and then hang.

**Comment by Mathias71BS** [comment]
This morning I've tried the v2.9.2.5 as portable from ZIP file (integrated in v2.9.2 folder). Before I had the latest stable with three instances of OGCS running without any problem. 

- I've added 3 profiles for 3 different 1:1 syncs. One direction and "confirm deletions" for all three profiles. 
- For each of them I've started with one day range and some test syncs afterwards (including no change, additions and deletions). Then I've increased the range step by step to 14 days in the past and 360 in the future. 

Until now it works without any problem! 

During my test I found some very minor issues, which do not limit the function and usability at all: 

- It syncs a date range 1 day more into the future than configured under Sync Settings > Sync options > When. 
- The button "Custom timezone Mapping" within Sync Settings > Outlook is placed at a strange location (see attached image), and the location changes sometimes. 

![image](https://user-images.githubusercontent.com/70021991/147082289-b45b9c97-06d8-49cd-b74f-4125428691f4.png)

Last, but not least: THANK YOU VERY MUCH, for this great SW!

**Comment by wir3z** [comment]
> Ok, this seems to be a MS problem. I ended up doing the "online repair" of office, and it's been flawless for the past 3 days again. Previously, it would only run for 4-6 hours and then hang.

Seems to have been the case.  Been working flawless since I did the Outlook repair several days ago.  

Only "nice thing" would be to move the Google Analytic call home failures from FAIL to something less critical.  I get a lot of log entries around this since my network blocks most of the ad sites.

**Comment by FabianBeiner** [comment]
Lovely to see this addition, @phw198. Thanks for that. :)

Do I need this version for the following scenario, or did I miss that I could do it with a “stable” one as well?

1. One Google Calendar, one Outlook Calendar. 
2. Every entry from the Google Calendar, that gets synced to Outlook, should get a specific color/label and set to private, as well as all the reminders from Google added.
3. Every entry from the Outlook Calendar, that gets synced to Google, should get a specific color as well as the reminders and stuff from Outlook.

I know, this is basically a two-way sync, but the color/label thingy didn't work for me. Thanks for any hints!

**Comment by NWH0** [comment]
Very nice to see this , @phw198. Thank you, I'm waiting for this feature for 2 years. :)

To bad, the alpha hotfix does not start on my system. I seems like it's killed in the moment it wants to start.

Do you need more information @phw198 how can I help?

**Comment by wir3z** [comment]
> Very nice to see this , @phw198. Thank you, I'm waiting for this feature for 2 years. :)
> 
> To bad, the alpha hotfix does not start on my system. I seems like it's killed in the moment it wants to start.
> 
> Do you need more information @phw198 how can I help?

Is this with the 2.9.2.5 release listed at the top?  I had your issue on one of the versions.  Might have been an issue with the settings file between the single and multiple profiles?

I just kept starting the app again, and on time #2 or #3 it was fine, and has been fine every since.  Maybe I rebooted as well?  

There wasn't a clear root cause.

**Comment by NWH0** [comment]
Thanks for your suggestions @Wir3z . I had this issue with 2.9.2.5 and also with the previous alpha version. I will try to replace the settings file with an empty one and get back to you.

Maybe it's an error related to issue #1341

**Comment by wir3z** [comment]
Maybe?  I did end up at one time "starting fresh" with a clean settings file, so that might be why I never had another problem.

**Comment by Malli88** [comment]
Is there a problem with the Sync Option of "Set entries as ...."?
Looks like the dropdown is synced overall profiles. Would be lovely if I could set the different calendars for different states.
Is there any Information that I can provide to help fixing that?

Best regards,
Stephan

**Comment by chasedonaldg** [comment]
Hello
I have been using the latest alpha for the day. I would like to confirm functionality if someone would be so kind to do so.
My situation:
I have 3 google calendars. I added 3 corresponding calendars in outlook under my default mailbox. I set up 3 profiles in OGCS that would sync each of the g calendars to the corresponding o calendars. OGCS is syncing but the 3 g calendar events are all combined and added to my default calendar, not each corresponding calendar set up under my 3 profiles in settings. Is this what is supposed to happen? I assumed that if you are able to choose a corresponding calendar for sync to outlook that it would place events to each from the google source calendars.

Any feedback is appreciated.

**Comment by wir3z** [comment]
> Hello I have been using the latest alpha for the day. I would like to confirm functionality if someone would be so kind to do so. My situation: I have 3 google calendars. I added 3 corresponding calendars in outlook under my default mailbox. I set up 3 profiles in OGCS that would sync each of the g calendars to the corresponding o calendars. OGCS is syncing but the 3 g calendar events are all combined and added to my default calendar, not each corresponding calendar set up under my 3 profiles in settings. Is this what is supposed to happen? I assumed that if you are able to choose a corresponding calendar for sync to outlook that it would place events to each from the google source calendars.
> 
> Any feedback is appreciated.

Are you using the 2.9.2.5 version at the top of this thread?  I had issues with the previous versions of the Alpha, but the above version has been rock solid so far.

**Comment by chasedonaldg** [comment]
> 

Yes. I may have setting wrong, but seems pretty straightforward? Am I able to post screenshots to see if setup is correct?

**Comment by wir3z** [comment]
> > 
> 
> Yes. I may have setting wrong, but seems pretty straightforward? Am I able to post screenshots to see if setup is correct?

I'd try deleting the "settings.xml" file and re-doing the setup again.  I did have some oddness when moving from one of the older alphas to the latest one.

**Comment by chasedonaldg** [comment]
> > > 
> > 
> > 
> > Yes. I may have setting wrong, but seems pretty straightforward? Am I able to post screenshots to see if setup is correct?
> 
> I'd try deleting the "settings.xml" file and re-doing the setup again. I did have some oddness when moving from one of the older alphas to the latest one.

I did that but no luck. Still not placing events in the corresponding calendars. No clue where to go from here. Have tried resetting a couple of times.

**Comment by wir3z** [comment]
When you say 3 outlook calendars, as in 3 different email accounts?  Or one account with 3 calendars?

I have 4 different Outlook mail accounts mapped to 4 Google calendars + 1 shared calendar mapped to another Google calendar.  All of them sync and update properly.

**Comment by chasedonaldg** [comment]
> When you say 3 outlook calendars, as in 3 different email accounts? Or one account with 3 calendars?
> 
> I have 4 different Outlook mail accounts mapped to 4 Google calendars + 1 shared calendar mapped to another Google calendar. All of them sync and update properly.

I created 3 additional calendars under the default calendar which is under one email account in outlook. They all show up as a selectable outlook calendar in the OGCS settings but they were not syncing correctly to each calendar. I am beginning to think I have to have a separate email (or data) account for each. I am going to test that out and see if it works that way.

**Comment by wir3z** [comment]
Hmmm... that would be a question for Paul (phw198) who gave us this gem.  I'm guessing it doesn't support that right now, or hasn't been developed out yet.

**Comment by SVNKoch** [comment]
> > When you say 3 outlook calendars, as in 3 different email accounts? Or one account with 3 calendars?
> > I have 4 different Outlook mail accounts mapped to 4 Google calendars + 1 shared calendar mapped to another Google calendar. All of them sync and update properly.
> 
> I created 3 additional calendars under the default calendar which is under one email account in outlook. They all show up as a selectable outlook calendar in the OGCS settings but they were not syncing correctly to each calendar. I am beginning to think I have to have a separate email (or data) account for each. I am going to test that out and see if it works that way.

Do you sync to one google calendar or each to a seperate one?
Asking because of first option, then you will mix them up if you have two way sync enabled, as Outlook A getrs synced to google and then gets two way synced back to Outlook B.

**Comment by chasedonaldg** [comment]
> > > When you say 3 outlook calendars, as in 3 different email accounts? Or one account with 3 calendars?
> > > I have 4 different Outlook mail accounts mapped to 4 Google calendars + 1 shared calendar mapped to another Google calendar. All of them sync and update properly.
> > 
> > 
> > I created 3 additional calendars under the default calendar which is under one email account in outlook. They all show up as a selectable outlook calendar in the OGCS settings but they were not syncing correctly to each calendar. I am beginning to think I have to have a separate email (or data) account for each. I am going to test that out and see if it works that way.
> 
> Do you sync to one google calendar or each to a seperate one? Asking because of first option, then you will mix them up if you have two way sync enabled, as Outlook A getrs synced to google and then gets two way synced back to Outlook B.

Yes I was trying to sync to 3 calendars under one email. I have since created 3 additional data files in outlook with a calendar under each  and syncing those calendars to its  corresponding google calendar. It was working great but I have had one event I created in calendar a that for some reason syncs to calendar b. Not sure what’s going on but will be troubleshooting.

**Comment by phw198** [comment]
Thanks @Mathias71BS - have fixed the button positioning problem. What timezone are you in? So if today was Monday, and you set it to sync one day in the future (Tuesday), it actually also syncs _single_ items (not recurrences) on the Wednesday?

**Comment by phw198** [comment]
> Only "nice thing" would be to move the Google Analytic call home failures from FAIL to something less critical. I get a lot of log entries around this since my network blocks most of the ad sites.

@wir3z It might be easier to just disable telemetry in the settings?

**Comment by phw198** [comment]
> Hmmm... that would be a question for Paul (phw198) who gave us this gem. I'm guessing it doesn't support that right now, or hasn't been developed out yet.

I can confirm that 3 Outlook calendars in the same account can be synced with different profiles to the same Google account - that's supported. However, as @SVNKoch called out, if you sync multiple Outlook calendars to a single Google calendar with two way configured, you're going to end up in a world of duplication hurt :grimacing: One way sync into Google is the only "safe" option here.

If two-way sync is needed, you'd need to sync each Outlook calendar to a dedicated calendar in the same Google account and then display then all overlaid.

> It was working great but I have had one event I created in calendar a that for some reason syncs to calendar b. Not sure what’s going on but will be troubleshooting.

@chasedonaldg Sounds like at some point the calendar item got onto both calendars and now the Google item has metadata against both of them. Probably best to set OGCS to one-way sync, delete the Google item and also from the incorrect Outlook calendar, sync to re-create the Google item from the correct calendar, turn back on two-way sync to original configuration.

--------

So.....it feels like it's time to start releasing this as an alpha! :tada:

A special thanks to @wir3z and to all the early adopters - your testing and feedback has been invaluable! :clap:

**Comment by phw198** [comment]
> I will try to replace the settings file with an empty one and get back to you. Maybe it's an error related to issue #1341

@NWH0 If you can provide your `OGcalsync.log` file after startup on v2.9.2.5 I'll take a closer look.

**Comment by phw198** [comment]
> I know, this is basically a two-way sync, but the color/label thingy didn't work for me. Thanks for any hints!

@FabianBeiner Yes, this sounds like you need to configure two one-way syncs in order to get the category/colour complexity correct...

**Comment by FabianBeiner** [comment]
> > I know, this is basically a two-way sync, but the color/label thingy didn't work for me. Thanks for any hints!
> 
> @FabianBeiner Yes, this sounds like you need to configure two one-way syncs in order to get the category/colour complexity correct...

I just wanted to set this up. I began with syncing Outlook to Google, so my business information is added to my personal calendar. However, with this setup, it wants to delete all the existing Google entries, instead of just adding the new ones. 🙈 I guess there is no way to achieve what I want.

**Comment by phw198** [comment]
> Is there a problem with the Sync Option of "Set entries as ...."? Looks like the dropdown is synced overall profiles. Would be lovely if I could set the different calendars for different states. Is there any Information that I can provide to help fixing that?

@Malli88 Yes, looks like there's a bug where that setting isn't loading properly between profiles. Will have a fix out for the next release :+1:

**Comment by phw198** [comment]
@FabianBeiner That would have happened with two-way sync too though. Did you forget to check the "Merge with existing" entries? I'd always recommend syncing to a dedicated "work" calendar in Google if possible though...

**Comment by FabianBeiner** [comment]
> @FabianBeiner That would have happened with two-way sync too though. Did you forget to check the "Merge with existing" entries? I'd always recommend syncing to a dedicated "work" calendar in Google if possible though...

No, I activated that option:

![image](https://user-images.githubusercontent.com/86269/152687361-18c10577-ccdf-45b8-ad88-aed4effe7088.png)

**edit:** This is probably due to the fact, that when I do this, there is nothing to merge. There are existing Google entries that I want to keep, but Outlook doesn't have them (yet). So it wants them to delete.

I'd love that the dedicated work/private calendars would work. But I need all of my appointments in one (Outlook) calendar; otherwise people will invite me to events where I'm already busy because they won't be able to see what I've added to my second calendar. (Outlook sadly only takes the main calendar into account when seeking someone's status, if available or not.)

**Comment by wir3z** [comment]
> > Only "nice thing" would be to move the Google Analytic call home failures from FAIL to something less critical. I get a lot of log entries around this since my network blocks most of the ad sites.
> 
> @wir3z It might be easier to just disable telemetry in the settings?

Well shoot.  I didn't realize that was even there.  Thanks!  (Not that I care about it doing metrics, just happens that the DNS black hole seems to block the google analytics along with all the other spamming ad sites).

**Comment by phw198** [comment]
@FabianBeiner In which case, OGCS must have at _some point_ seen the items in Google and synced them to Outlook calendar, but they are no longer in Outlook so it's trying to delete them. As far as I can tell, what you're attempting should be possible, but your configs and syncs have got rather muddled - so I don't think this is specific to Profiles, and should be really be investigated under a different issue. That said, if you do a G->O sync, I think that should create the "missing" items and then when you revert back to O->G sync, it won't try and delete them.
