### ISSUE TITLE
Word Obfuscation eventually incorrectly overwrites the source meeting subject in Google

### ISSUE THREAD

**Issue by GFlolid** [phw198/OutlookGoogleCalendarSync#1399]
:memo: Use the below template to report your issue.  
:bulb: Upgrade to the latest alpha release to check if the problem is already fixed.  
:paperclip: To aid investigation, provide your OGcalsync.log file ([see instructions](https://github.com/phw198/OutlookGoogleCalendarSync/wiki/Reporting-problems#locating-your-ogcalsynclog-file)).  

----

**OGCS Version**:  2.9.3.0
**Installed or Portable**: Installed

**Problem Description**  
Word Obfuscation eventually overwrite the source meeting subject in Google

**Steps to Reproduce the Issue**  
1) I am syncing (-20days, 72days) one way a calendar from OUTLOOK1 to GOOGLEMAIN for work.  GOOGLEMAIN is my master calendar.  No issues are apparent . I synch everything except meeting attendees.

2) With another profile, I am doing two way synching (-0days, 7days) between another calendar OUTLOOK2 to GOOGLEMAIN for work with another client.  I only sync meeting subject for privacy. The two way synching is so that free/busy time  is accurate to allow the client to schedule meetings with me during free time.  I also use obfuscation for privacy here changing all GOOGLEMAIN meeting subjects to "Private Event" in OUTLOOK2.  This seems to work initially, but eventually ends up overwriting most of the source meetings in GOOGLEMAIN with "Private Event" as the subject.  I have not been able to see the pattern when or why this happens.

  
\<Update here>

**Comment by GFlolid** [comment]
I uploaded a log file which shows the incorrect changing of the correct subject to "Private Event" on line 396.
I am not sure if I can find the log file where the meeting that matches this one in Outlook was created by ocgs

**Comment by phw198** [comment]
This seems to be a long standing bug! I replicated it with:

1. Sync bi-directional and confirm obfuscation occurred correctly G->O.
2. Open the Outlook item and make some kind of edit (not to the subject though, eg location), Save.
3. Sync bi-directional and confirm Google subject has now been changed incorrectly.

:package: Could you see if it's resolved with [hotfix v2.6.3.6.zip](https://github.com/phw198/OutlookGoogleCalendarSync/files/8241087/v2.6.3.6.zip) ([see instructions for applying](https://github.com/phw198/OutlookGoogleCalendarSync/wiki/Reporting-Problems#applying-a-hotfix))?

Please let me know how it goes.

**Comment by GFlolid** [comment]
Paul,

I applied the hotfix.  The only thing I synch from Google to Outlook is the
meeting title itself (for privacy).

My google calendar is still getting overwritten with my obfuscation text
"Private Event".  I did a full sync from Google to Outlook which may have
made things worse.

I am curious if you have a hard rule to not update the meeting title in
Google(source) if the meeting title in Outlook(target) is equal to the
obfuscation text ("Private Event" for me)?

I don't know all the use cases but I am fairly sure this would work for
me.  I never want my Google meeting titles overwritten with the obfuscation
text.



regards,

Greg Flolid

**Comment by GFlolid** [comment]
Cancel my last email.  I had the direction of obfuscation incorrect.  Let
me keep testing.

regards,

Greg Flolid

**Comment by phw198** [comment]
@GFlolid Testing has gone OK then? Are we good to include this in the next release?

**Comment by GFlolid** [comment]
It seems to have worked for about a week, but I was going to give it another week before I confirmed it to you.

**Comment by GFlolid** [comment]
I am back home now.  The hotfix seems to be working.  Certainly better than without the fix so I would suggest you put it in the next release unless it messes with a bunch of other stuff.

**Comment by GFlolid** [comment]
Thanks for fixing the issue


best regards,

Greg Flolid
Flolid Consulting LLC
***@***.***
(281)845-2250
