### ISSUE TITLE
v2.9.4: You modified an item in this series and that instance no longer exists. Close any open items and try again.

### ISSUE THREAD

**Issue by efranz** [phw198/OutlookGoogleCalendarSync#1432]
[See comment lower down for available hotfix](https://github.com/phw198/OutlookGoogleCalendarSync/issues/1432#issuecomment-1107851615).

-------

2022-04-15 05:52:38,149 ERROR  11 OutlookGoogleCalendarSync.Console [278] -  Sie haben ein Element dieser Serie geändert, und diese Instanz ist nicht mehr vorhanden. Schließen Sie alle geöffneten Elemente, und versuchen Sie es erneut.
2022-04-15 05:52:38,149 ERROR  11 OutlookGoogleCalendarSync.Console [278] -  If this keeps happening, please restart OGCS.

logfile attached

**Comment by efranz** [comment]
[OGcalsync.log](https://github.com/phw198/OutlookGoogleCalendarSync/files/8493765/OGcalsync.log)

**Comment by RHG2208** [comment]
Good morning, I have the same issue.

**Comment by RHG2208** [comment]
[OGcalsync.log](https://github.com/phw198/OutlookGoogleCalendarSync/files/8499477/OGcalsync.log)

**Comment by phw198** [comment]
@efranz I don't see any evidence in the logs of you following the suggested restart of OGCS? Did a restart make any difference? If not, try stopping both OGCS and Outlook and then running them again.

**Comment by MortenAnd** [comment]
I have the same issue. Running Win 11 
I have downgraded to version 2.9.3 and now it works again.
![syncIssue](https://user-images.githubusercontent.com/75125288/163950802-248be37d-4b4a-44f5-b136-ba24371748dd.png)
[OGcalsync.log](https://github.com/phw198/OutlookGoogleCalendarSync/files/8510892/OGcalsync.log)

**Comment by RHG2208** [comment]
The same for me. The previous version works fine. Reinstalling 2.9.4 doesn't help.

Outlook voor Android<https://aka.ms/AAb9ysg> downloaden
________________________________

**Comment by SVNKoch** [comment]
restarting and full sync didn't fix the problem for me

**Comment by NeoMatrixJR** [comment]
I am also having this issue.  Restarting, one-way then 2-way sync did not resolve.

**Comment by tnjgb** [comment]
Same issue here. I thought it was a recurring appointment where some occurrences have been removed but on deleting the whole series in both Outlook and Google, the error still occurs. I have reverted to 2.9.3 for now.

**Comment by phw198** [comment]
:package: This should now be resolved with [hotfix v2.9.4.6.zip](https://github.com/phw198/OutlookGoogleCalendarSync/files/8549868/v2.9.4.6.zip) ([see instructions for applying](https://github.com/phw198/OutlookGoogleCalendarSync/wiki/Reporting-Problems#applying-a-hotfix)).

Note, this is patched on top of #1422, v2.9.4.3.

Please let me know how it goes.

**Comment by tnjgb** [comment]
2.9.4.6 seems to fix this issue. However there seems to be a new issue in that the scheduled Sync is not happening. The first Sync happens around a minute after the app opens then it shows the last successful time then the next scheduled time (set to every 5 mins using personal Client ID) but the Sync does not happen at the next scheduled time. The Sync has finished but still shows the "Stop Sync" button. Push Syncs from Outlook are also not happening.

Update: Scheduled syncs will run as long as there has not been a push sync from Outlook or a manual sync. The first push sync from Outlook will work then no further syncs other than manual will occur.

![Screenshot 2022-04-24 174328](https://user-images.githubusercontent.com/70089616/164987007-ea4ced55-23ea-463c-bee6-7e82cc514896.png)

**Comment by phw198** [comment]
@tnjgb Thanks for testing that so quickly. I've created #1443 to cover the new issue you are reporting, so will triage it under that.

**Comment by Aerics84** [comment]
Thanks for the fix. It solved the problem for me, too.

**Comment by teendoc** [comment]
Looks like my issue has been resolved. Thank you.

**Comment by RHG2208** [comment]
Thank you!
