### ISSUE TITLE
Outlook version 2309 hangs as soon as OutlookGoogleCalendarSync is started

### ISSUE THREAD

**Issue by Moonbird-IT** [phw198/OutlookGoogleCalendarSync#1754]
> Checklist:
> * [x] [Upgrade](https://github.com/phw198/OutlookGoogleCalendarSync/wiki/Upgrading) to the latest release (alpha if available) ![latest release](https://img.shields.io/github/release/phw198/OutlookGoogleCalendarSync/all.svg)
> * [x] Reproduce the issue
> * [x] Complete the information below
> * [x] Provide your `OGcalsync.log` file (see [how-to](https://github.com/phw198/OutlookGoogleCalendarSync/wiki/Reporting-problems#locating-your-ogcalsynclog-file))

**OGCS Version**: v2.10.2.0
**Edition**: Installed
**Sync Direction**:  O->G

**Bug Description**  
Outlook stops responding after OutlookGoogleCalendarSync has been started. Outlook shows a grayed out overlay and can no longer be used. In the Task Manager, Outlook is reported as "not responding". OGCS shows 0% CPU usage, sometimes a bit above 0% (like 0.4%). Even after 20 minutes of waiting, Outlook remains unresponsive. When killing the OGCS process, Outlook becomes responsive after several minutes.
I tried running Outlook and OGCS with administrative privileges, behavior remains the same as mentioned before. Also tried restarting Windows. Error first occurred with v2.10.0.0, no change with current alpha version.

**Steps to Reproduce the Issue**  
1. Launch Outlook
2. Launch OGCS
3. Outlook hangs

Alternative approach:
1. Launch OGCS, which launches Outlook
2. Outlook hangs

**Any other information**  
Microsoft 365, Outlook version 2309 (Build 16827.20278 Click-to-run), with connected Sharepoint and Onedrive services.
[OGcalsync.log](https://gist.github.com/Moonbird-IT/b4302954c3bfafa13e6ba99ca870c4e4)

**Comment by Moonbird-IT** [comment]
After waiting for about an hour and when using the alpha version, Outlook became responsive again and the syncing also works now without hanging Outlook.

**Comment by phw198** [comment]
Bit of an odd one - I assume maybe there was a slow connection to your Exchange server or something, or there was a problem with the OST file which is now resolved.

Unfortunately, your log level is configured to `OFF`, so nothing useful captured in the logfile to diagnose any further.

**Comment by Moonbird-IT** [comment]
@phw198 the problem appeared again on my device this morning, luckily I had set the log level to DEBUG before I had restarted Windows. Outlook has been hanging for about 2 hours now (started Outlook and OGCS at ~ 8:35 AM this morning, now it's 10:40). OGCS is at 0% CPU usage, sometimes jumps to 0.3%. The last entries in the log file are:

> 2023-12-18 08:36:35,081 DEBUG  1 OutlookGoogleCalendarSync.OutlookOgcs.OutlookNew [65] -  Get the folders configured in Outlook
> 2023-12-18 08:36:35,088 DEBUG  1 OutlookGoogleCalendarSync.OutlookOgcs.OutlookNew [431] -  Finding default Mailbox calendar folders
> 2023-12-18 08:36:35,416 INFO  20 OutlookGoogleCalendarSync.Updater [254] -  Already running the latest version of OGCS.

This morning, Outlook prompted to me to sign in via Microsoft Account, signing in worked correctly, but the popup window of the authentication is still being shown and Outlook is not responding.

![image](https://github.com/phw198/OutlookGoogleCalendarSync/assets/2480138/c9ad27aa-88d8-400e-9d06-fe296326ba38)

![image](https://github.com/phw198/OutlookGoogleCalendarSync/assets/2480138/325bb549-5b5f-40e3-bc46-fa3c911bbd45)

The tray icon of OGCS is also not visible in the system tray.

I'll keep on waiting until Outlook reacts again, I'll attach the log file, once the applications are responsive again.

**Comment by Moonbird-IT** [comment]
Afer nearly 4 hours wait time, Outlook became responsive again. Here's the log file:

[OGcalsync.log](https://gist.github.com/Moonbird-IT/d84be063aa62602a2e25602381c5ebea)

**Comment by phw198** [comment]
The log file shows
1. Outlook already running in cached disconnected mode
2. OGCS starts and attempts to connect
3. 4 hours later Outlook is closed
4. OGCS then starts its own instance of Outlook
5. After 12 minutes of try to access it fails

This looks like a very similar issue to #1660, which was down to a public folder no longer being accessible. You've redacted your logfile, so I can't tell what folder it couldn't access but you have `Failed to get EntryID for folder: [REDACTED]` - was this a public folder?

**Comment by Moonbird-IT** [comment]
@phw198 sorry for the late reply. The "REDACTED" was my local user name on Windows, the OST files are local, but it might be that they are also being synced by OneDrive. The problem still persists, but it is not as severe as before: after each boot of the machine - normally I just suspend the device -, Outlook hangs for several minutes while OGCS is running, but will eventually be usable again. 
For me, the issue can be closed, as I can live with the current situation.

**Comment by phw198** [comment]
Thanks for updating me @Moonbird-IT - will close this, as you suggested.
