### ISSUE TITLE
11-Mar-2024 Google returns working locations - OGCS errors

### ISSUE THREAD

**Issue by pjhack** [phw198/OutlookGoogleCalendarSync#1817]
**OGCS Version**: v2.10.0.0  
**Edition**: Installed
**Sync Direction**: O<->G

> workingLocationProperties requires an event type of workingLocation, and vice versa. [400=BadRequest]

**Bug Description**  
Suddenly sync fails with error:
`ERROR  14 OutlookGoogleCalendarSync.Console [292] -  workingLocationProperties requires an event type of workingLocation, and vice versa. [400=BadRequest]`

Letting the sync finish, OGCS creates on Outlook a daily event for each work location defined on Google.
Desired behaviour: OGCS ignoring working locations or properly handling them.

**Steps to Reproduce the Issue**  
1. Create a working location on google calendar (even for 1 day only)
2. Push sync on OGCS

**Any other information**  
I always had working locations defined on Google and never changed them. OGCS always worked fine untill this afternoon.
[OGcalsync.log](https://github.com/phw198/OutlookGoogleCalendarSync/files/14561921/OGcalsync.log)

**Comment by phw198** [comment]
Hi @pjhack thanks for reporting this.

However, the [documentation says](https://developers.google.com/calendar/api/v3/reference/events/list) by default Working Locations aren't returned, only regular, focus time and out of office.

So are you still seeing this problem or was it a transient problem? As you say it wasn't a problem before, I wonder if Google just messed something up for a bit... 🤞🏻

**Comment by phw198** [comment]
Bugger, found the [email referenced here](https://community.make.com/t/google-calendar-api-v3-changes-starting-march-11-2024/26786) buried in my inbox. OK, so this is a rather awesome breaking change Google introduced with barely a month's notice and they haven't even updated their own documentation yet 🙄

**Comment by phw198** [comment]
:package: Please check if this is resolved with [hotfix v2.10.3.5.zip](https://github.com/phw198/OutlookGoogleCalendarSync/files/14624505/v2.10.3.5.zip) ([see instructions for applying](https://github.com/phw198/OutlookGoogleCalendarSync/wiki/Reporting-Problems#applying-a-hotfix)).
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; [CRCs](https://github.com/phw198/OutlookGoogleCalendarSync/wiki/Known-Issues#cyclic-redundancy-checks---aka-crcs): Zip = `FE28312C` Exe = `FAFDB264`

:arrow_double_up: Please make sure you upgrade to ![latest release](https://img.shields.io/github/release/phw198/OutlookGoogleCalendarSync/all.svg) by going to the `About` tab in OGCS, ticking the `Check for Alpha releases` box and then clicking `Check for Update` - then applying the hotfix.

**Comment by pjhack** [comment]
Thank you. That was fast!
The hotfix works. No more errors trying to synchronize WorkingLocations as events.
One thing only (for ppl reading): at the moment, 2.10.3-alpha cannot be automatically downloaded with "check for aplpha release > check for updates" (it downloads 2.10.2-alpha). We had to manually download it from here [https://github.com/phw198/OutlookGoogleCalendarSync/releases/tag/v2.10.3-alpha](https://github.com/phw198/OutlookGoogleCalendarSync/releases/tag/v2.10.3-alpha).

**Comment by Fafner1976** [comment]
I think he pulled it from the auto update series due to an important bug many reported, and that was fixed with a 2.10.3.x hotfix. Next official release will be 2.10.4.

**Comment by lestarte** [comment]
Hi.
I still struggle with this problem. I did the following steps:
- Tried setting it to include ALPHA versions and pressed UPDATE.
Normally it always hangs then but after shooting it down with task manager and re-starting it, it seems to work, then.
- C:\Users\myuser\AppData\Local\OutlookGoogleCalendarSync\app-2.10.4-alpha does now exist and seems therefore to be installed properly.
- Applied the hotfix manually.
(I've read and did everything as stated at https://github.com/phw198/OutlookGoogleCalendarSync/wiki/Reporting-Problems#applying-a-hotfix )
- When starting either the .EXE in this folder manually or the .EXE one folder above (..\) which has ~270 KB), every time in the about field it still says Version 2.10.3.5.
What could be the culprit here? I really don't understand it and the problem sadly sadly so annoying...
Thanks,
Olli

**Comment by phw198** [comment]
@lestarte Your post is a little confused. If you already had alpha v2.10.4 installed then there is no need to _then_ patch it to a _previous_ hotfix. If you are still experiencing the problem on 2.10.4, then you need to upload your logfile after you have encountered the issue.

**Comment by lestarte** [comment]
Hi Paul. Thanks for your reply.
You wrote 
```
Please check if this is resolved with [hotfix v2.10.3.5.zip](https://github.com/phw198/OutlookGoogleCalendarSync/files/14624505/v2.10.3.5.zip) ([see instructions for applying](https://github.com/phw198/OutlookGoogleCalendarSync/wiki/Reporting-Problems#applying-a-hotfix)).
      [CRCs](https://github.com/phw198/OutlookGoogleCalendarSync/wiki/Known-Issues#cyclic-redundancy-checks---aka-crcs): Zip = FE28312C Exe = FAFDB264

⏫ Please make sure you **upgrade to latest release by going to the About tab in OGCS**, ticking the Check for Alpha releases box and then clicking Check for Update - **then applying the hotfix.**
```

That's why I did it that way...
Maybe this seemed too confusing for me ;)
I've backuped the old EXE and PBP files and moved them back.
Now it says 2.10.4.0.
Still, the problem occurs for me, sadly... Here is the log:
[OGcalsync.log](https://github.com/phw198/OutlookGoogleCalendarSync/files/14975635/OGcalsync.log)

Olli

**Comment by hakarune** [comment]
I installed the alpha and the hotfix and still getting this error

**Comment by hakarune** [comment]
Here is my log from alpha 2.10.4


[OGcalsync_obfuscated.log](https://github.com/phw198/OutlookGoogleCalendarSync/files/14984891/OGcalsync_obfuscated.log)

**Comment by phw198** [comment]
@lestarte Yes, I wrote that before the fix was confirmed and rolled into the next alpha release 🙂 

Thanks for providing your log file though - I have confirmed this is a different permutation of the same underlying problem. I have raised #1843 to track it and will be posting a hotfix shortly.
