### ISSUE TITLE
v2.11.2 falsely detecting start/end time changed (by number of hours offset from UTC)

### ISSUE THREAD

**Issue by phw198** [phw198/OutlookGoogleCalendarSync#2047]
**OGCS Version**: v2.11.2  

**Bug Description**  
OGCS incorrectly detects changes in start and end times for Google events, due to comparisons in UTC not localtime.

**Steps to Reproduce the Issue**  
Full or delta syncs report a change in start and/or end time when there is none. The difference in time is the offset between localtime and UTC.

**Comment by phw198** [comment]
:package: This should now be resolved with [hotfix v2.11.2.1.zip](https://github.com/user-attachments/files/18470582/v2.11.2.1.zip) (see [instructions for applying](https://github.com/phw198/OutlookGoogleCalendarSync/wiki/Reporting-Problems#applying-a-hotfix)).
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; [CRCs](https://github.com/phw198/OutlookGoogleCalendarSync/wiki/Known-Issues#cyclic-redundancy-checks---aka-crcs): Zip = `F6A3BA15` Exe = `8197E679`

Please let me know how it goes, if you apply the hotfix.

**Comment by TheJacksonian** [comment]
I know I'm not the original reporter, but I too had this issue on 2 recurring meetings and 2 seperate meetings I'd added after moving to the new Aplha.  
The hotfix has resolved the issue for me. The meetings have returned to their correct time.

**Comment by timothy-holmes** [comment]
I can also confirm hotfix resolved this issue. Needed to do a full sync to revert to the correct times.

**Comment by jrhalasz** [comment]
The hotfix resolved the issue after a full sync.

**Comment by d-treegardener** [comment]
I have an additional problem described here: https://github.com/phw198/OutlookGoogleCalendarSync/issues/1978#issuecomment-2607200498
Even after the full sync, I still get these offset errors.
Also I think the time shift is sometimes still wrong. But have to check that again tomorrow. Will add more information, if it's really still wrong.

**Comment by emotionstudy4** [comment]
The hotfix corrected the bug for me. Thanks for all your hard work!

**Comment by phw198** [comment]
Thanks everyone for confirming the fix 👍🏻 

As this is a high impact bug, I've quietly patched the ZIP and setup.exe on v2.11.2.0 for new installers; unfortunately upgraders will have to [apply the hotfix on this page](https://github.com/phw198/OutlookGoogleCalendarSync/issues/2047#issuecomment-2601036533).

@lemonbutter we'll track your issue over on #1978, as it predates the bug that caused the problem on this issue.

**Comment by joedotbloggs** [comment]
Hi, this has fixed the problem when viewing items in the calendar that are synced from google cal to outlook cal. 
The entries are now at the correct time - so amazing and Thankyou!

But there may still bepart of the bug not fixed - ie. in the csv's produced and in the OGCS sync verbose output, the timestamp on the text displayed/logged is still incorrect. 
It seems to be not respecting the timezone offset - eg. in the outlook_create.csv, the "starttime" and "Endtime" shows eg. "5/02/2025 6:50:00 AM +00:00" which maybe in my example should really likely read as something like "5/02/2025 6:50:00 AM +08:00"?
And the sync log shows "And the OGCS app sync log tab (with verbose logging ticked) shows "5/02/2025 6:50:00 AM <Blah Event Name>" but should show "5/02/2025 2:50:00 PM <Blah Event Name>".

**Comment by phw198** [comment]
@joedotbloggs You are indeed correct and I had already coded a fix, but just not built a hotfix for it as no one had spotted it yet!

:package: If you would like to confirm [hotfix v2.11.2.6.zip](https://github.com/user-attachments/files/18694287/v2.11.2.6.zip) does indeed resolve it, it would appreciated though (see [instructions for applying](https://github.com/phw198/OutlookGoogleCalendarSync/wiki/Reporting-Problems#applying-a-hotfix)).
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; [CRCs](https://github.com/phw198/OutlookGoogleCalendarSync/wiki/Known-Issues#cyclic-redundancy-checks---aka-crcs): Zip = `7BFFA637` Exe = `6A844883`

**Comment by joedotbloggs** [comment]
> 📦 If you would like to confirm [hotfix v2.11.2.6.zip](https://github.com/user-attachments/files/18694287/v2.11.2.6.zip) does indeed resolve it, it would appreciated though (see [instructions for applying](https://github.com/phw198/OutlookGoogleCalendarSync/wiki/Reporting-Problems#applying-a-hotfix)).       [CRCs](https://github.com/phw198/OutlookGoogleCalendarSync/wiki/Known-Issues#cyclic-redundancy-checks---aka-crcs): Zip = `7BFFA637` Exe = `6A844883`

This hotfix (2.11.2.6) works - fixes both the CSV's and the Verbose Log! 
Thank you :)

**Comment by rafi-d** [comment]
The hotfix is not fixing the issue for EXISTING items in Google. ONLY if I am changing them a bit - like adding 5 minutes  and re-syncing -  it is fixing the wrong entry in outlook!

**Comment by phw198** [comment]
@rafi-d For fixing already syncing items you either need to edit the Outlook item(s), or run a full sync from O->G.

**Comment by rafi-d** [comment]
What about from G to O?  Your bug was in Outlook times (in my use case)
Edit: Got it, thanks, needed to change from two ways sync to G-to-O  (v 2.11.2.1)

**Comment by buckaroo54** [comment]
I'm still having the issue that @rafi-d had, with past appointments not updating. I tried hotfixes 2.11.2.1, 2.11.2.3, 2.11.2.4, and 2.11.2.6. It compares all of the entries and says that none of them need to be updated, even though the past Google Calendar entries are in the correct time and the same past Outlook entries are not. The sync is set Outlook <-- Google. Any ideas?

**Comment by phw198** [comment]
@buckaroo54 You're running a full sync or a delta sync? Either press `Shift` and click `Sync`, or use the dropdown on the Sync button...

**Comment by buckaroo54** [comment]
I was _not_ running a full sync 🙃 Thank you for the guidance, all's well now! 😁👍
