### ISSUE TITLE
v2: The UTC time represented after applying the offset must be between years 0 and 10000.

### ISSUE THREAD

**Issue by phw198** [phw198/OutlookGoogleCalendarSync#2055]
Splitting it out from #1978, as the root cause seems different from v3.

> @phw198 Here the new logfile from my side:
> 
> ```
> 2025-01-28 08:53:17,179 INFO  1  OutlookGoogleCalendarSync.Google.ErrorReporting [0] -  Turned error reporting OFF
> 2025-01-28 08:53:17,191 INFO  1  OutlookGoogleCalendarSync.Program [0] -  Program started: v2.11.2.3
> 2025-01-28 08:53:17,191 INFO  1  OutlookGoogleCalendarSync.Program [0] -  Started interactively.
> 2025-01-28 08:53:17,192 INFO  1  OutlookGoogleCalendarSync.Program [0] -  Logging to: C:\Daten\Programme\Portable_OGCS_v2.11.2\OGcalsync.log
> 2025-01-28 08:53:17,192 INFO  1  OutlookGoogleCalendarSync.Program [0] -  Purging log files older than 30 days...
> 2025-01-28 08:53:17,193 INFO  1  OutlookGoogleCalendarSync.Program [0] -  Purge complete.
> 2025-01-28 08:53:17,193 INFO  1  OutlookGoogleCalendarSync.Settings [0] -  Running OGCS from C:\Daten\Programme\Portable_OGCS_v2.11.2\OutlookGoogleCalendarSync.exe
> 2025-01-28 08:53:17,194 INFO  1  OutlookGoogleCalendarSync.Program [0] -  Storing user files in directory: C:\Daten\Programme\Portable_OGCS_v2.11.2
> 2025-01-28 08:53:17,194 DEBUG 1  OutlookGoogleCalendarSync.Telemetry [0] -  Settings not loaded; checking if the raw settings file has Gmail account set.
> 2025-01-28 08:53:17,197 DEBUG 1  OutlookGoogleCalendarSync.Google.Authenticator [0] -  Getting MD5 hash for '***********@gmail.com'
> 2025-01-28 08:53:17,197 DEBUG 1  OutlookGoogleCalendarSync.XMLManager [0] -  Retrieved setting 'CloudLogging' with value 'true'
> 2025-01-28 08:53:17,198 INFO  1  OutlookGoogleCalendarSync.Google.ErrorReporting [0] -  Turned error reporting ON
> 2025-01-28 08:53:17,198 DEBUG 1  OutlookGoogleCalendarSync.XMLManager [0] -  Retrieved setting 'Portable' with value 'true'
> 2025-01-28 08:53:17,199 DEBUG 1  OutlookGoogleCalendarSync.XMLManager [0] -  Retrieved setting 'LoggingLevel' with value 'WARN'
> 2025-01-28 08:53:17,199 INFO  1  OutlookGoogleCalendarSync.Settings [0] -  Logging level configured to 'WARN'
> 2025-01-28 08:53:24,895 WARN  1  OutlookGoogleCalendarSync.Forms.Main [0] -  Outlook calendar selection changed to: Kalender (ID: ***)
> 2025-01-28 08:54:36,210 WARN  12 OutlookGoogleCalendarSync.Console [0] -  If they exist in Google, they may get deleted. To avoid deletion, uncheck "Delete synced items if excluded". Recover unintentional deletions from the Google 'Bin'.If prompted to confirm deletion and you opt not to delete them, this will reoccur every sync. Consider assigning an excluded colour to those items in Google.
> 2025-01-28 08:54:36,212 WARN  12 OutlookGoogleCalendarSync.Console [0] -  See the wiki for tips if needing to resolve duplicates.
> 2025-01-28 08:58:43,608 FAIL  12 OutlookGoogleCalendarSync.Google.Calendar [0] -  The service calendar has thrown an exception. HttpStatusCode is PreconditionFailed. Precondition Failed
> 2025-01-28 08:58:43,622 WARN  12 OutlookGoogleCalendarSync.Google.Calendar [0] -  The Event has changed since it was last retrieved - attempting to force an overwrite.
> 2025-01-28 08:58:43,731 WARN  12 OutlookGoogleCalendarSync.Exception [0] -  Failed forcing save with ETagAction.Ignore
> 2025-01-28 08:58:43,732 FAIL  12 OutlookGoogleCalendarSync.Exception [0] -  Google.GoogleApiException: The service calendar has thrown an exception. HttpStatusCode is BadRequest. Invalid sequence value. The specified sequence number is below the current sequence number of the resource. Re-fetch the resource and use its sequence number on the following request.
> 2025-01-28 08:58:43,736 FAIL  12 OutlookGoogleCalendarSync.Exception [0] -  Code: 0x80131500,-2146233088; Location: MoveNext() in <Unknown File>
> 2025-01-28 08:58:43,833 WARN  12 OutlookGoogleCalendarSync.Google.Calendar [0] -  Attempting trample of remote version...
> 2025-01-28 08:58:44,703 FAIL  12 OutlookGoogleCalendarSync.Google.Calendar [0] -  The service calendar has thrown an exception. HttpStatusCode is PreconditionFailed. Precondition Failed
> 2025-01-28 08:58:44,704 WARN  12 OutlookGoogleCalendarSync.Google.Calendar [0] -  The Event has changed since it was last retrieved - attempting to force an overwrite.
> 2025-01-28 08:58:44,812 WARN  12 OutlookGoogleCalendarSync.Exception [0] -  Failed forcing save with ETagAction.Ignore
> 2025-01-28 08:58:44,813 FAIL  12 OutlookGoogleCalendarSync.Exception [0] -  Google.GoogleApiException: The service calendar has thrown an exception. HttpStatusCode is BadRequest. Invalid sequence value. The specified sequence number is below the current sequence number of the resource. Re-fetch the resource and use its sequence number on the following request.
> 2025-01-28 08:58:44,813 FAIL  12 OutlookGoogleCalendarSync.Exception [0] -  Code: 0x80131500,-2146233088; Location: MoveNext() in <Unknown File>
> 2025-01-28 08:58:44,910 WARN  12 OutlookGoogleCalendarSync.Google.Calendar [0] -  Attempting trample of remote version...
> 2025-01-28 08:58:46,604 ERROR 12 OutlookGoogleCalendarSync.Console [0] -  03.02.2025 14:00 => "ec1231c3d53e4af35daf2c83ae17f028"
> 2025-01-28 08:58:46,606 ERROR 12 OutlookGoogleCalendarSync.Console [0] -  Appointment update failed.
> 2025-01-28 08:58:46,606 ERROR 12 OutlookGoogleCalendarSync.Exception [0] -  System.ArgumentOutOfRangeException: Die nach dem Anwenden des Offsets dargestellte UTC-Zeit muss zwischen den Jahren 0 und 10000 liegen.
> Parametername: offset
> 2025-01-28 08:58:46,607 ERROR 12 OutlookGoogleCalendarSync.Exception [0] -  Code: 0x80131502,-2146233086; Location: ValidateDate() in <Unknown File>
> 2025-01-28 08:58:46,607 ERROR 12 OutlookGoogleCalendarSync.Exception [0] -     bei System.DateTimeOffset.ValidateDate(DateTime dateTime, TimeSpan offset)
>    bei System.DateTimeOffset..ctor(DateTime dateTime)
>    bei System.DateTimeOffset.op_Implicit(DateTime dateTime)
>    bei OutlookGoogleCalendarSync.Outlook.Calendar.UpdateCalendarEntry(AppointmentItem& ai, Event ev, Int32& itemModified, Boolean forceCompare)
>    bei OutlookGoogleCalendarSync.Outlook.Calendar.UpdateCalendarEntries(Dictionary`2 entriesToBeCompared, Int32& entriesUpdated)
> 2025-01-28 08:58:48,425 ERROR 12 OutlookGoogleCalendarSync.Console [0] -  31.01.2025 10:00 => "d0d76feb250a37d7beae4035c0be1f36"
> 2025-01-28 08:58:48,426 ERROR 12 OutlookGoogleCalendarSync.Console [0] -  Appointment update failed.
> 2025-01-28 08:58:48,426 ERROR 12 OutlookGoogleCalendarSync.Exception [0] -  System.ArgumentOutOfRangeException: Die nach dem Anwenden des Offsets dargestellte UTC-Zeit muss zwischen den Jahren 0 und 10000 liegen.
> Parametername: offset
> 2025-01-28 08:58:48,427 ERROR 12 OutlookGoogleCalendarSync.Exception [0] -  Code: 0x80131502,-2146233086; Location: ValidateDate() in <Unknown File>
> 2025-01-28 08:58:48,427 ERROR 12 OutlookGoogleCalendarSync.Exception [0] -     bei System.DateTimeOffset.ValidateDate(DateTime dateTime, TimeSpan offset)
>    bei System.DateTimeOffset..ctor(DateTime dateTime)
>    bei System.DateTimeOffset.op_Implicit(DateTime dateTime)
>    bei OutlookGoogleCalendarSync.Outlook.Calendar.UpdateCalendarEntry(AppointmentItem& ai, Event ev, Int32& itemModified, Boolean forceCompare)
>    bei OutlookGoogleCalendarSync.Outlook.Calendar.UpdateCalendarEntries(Dictionary`2 entriesToBeCompared, Int32& entriesUpdated)
> 2025-01-28 08:58:49,369 ERROR 12 OutlookGoogleCalendarSync.Console [0] -  04.02.2025 09:00 => "8c8779d374579777b4998297daeb2c95"
> 2025-01-28 08:58:49,370 ERROR 12 OutlookGoogleCalendarSync.Console [0] -  Appointment update failed.
> 2025-01-28 08:58:49,370 ERROR 12 OutlookGoogleCalendarSync.Exception [0] -  System.ArgumentOutOfRangeException: Die nach dem Anwenden des Offsets dargestellte UTC-Zeit muss zwischen den Jahren 0 und 10000 liegen.
> Parametername: offset
> 2025-01-28 08:58:49,370 ERROR 12 OutlookGoogleCalendarSync.Exception [0] -  Code: 0x80131502,-2146233086; Location: ValidateDate() in <Unknown File>
> 2025-01-28 08:58:49,371 ERROR 12 OutlookGoogleCalendarSync.Exception [0] -     bei System.DateTimeOffset.ValidateDate(DateTime dateTime, TimeSpan offset)
>    bei System.DateTimeOffset..ctor(DateTime dateTime)
>    bei System.DateTimeOffset.op_Implicit(DateTime dateTime)
>    bei OutlookGoogleCalendarSync.Outlook.Calendar.UpdateCalendarEntry(AppointmentItem& ai, Event ev, Int32& itemModified, Boolean forceCompare)
>    bei OutlookGoogleCalendarSync.Outlook.Calendar.UpdateCalendarEntries(Dictionary`2 entriesToBeCompared, Int32& entriesUpdated)
> 2025-01-28 08:58:50,072 ERROR 12 OutlookGoogleCalendarSync.Console [0] -  30.01.2025 08:45 => "f603fc1e94f7a399aca7e2283ec821b1"
> 2025-01-28 08:58:50,073 ERROR 12 OutlookGoogleCalendarSync.Console [0] -  Appointment update failed.
> 2025-01-28 08:58:50,073 ERROR 12 OutlookGoogleCalendarSync.Exception [0] -  System.ArgumentOutOfRangeException: Die nach dem Anwenden des Offsets dargestellte UTC-Zeit muss zwischen den Jahren 0 und 10000 liegen.
> Parametername: offset
> 2025-01-28 08:58:50,073 ERROR 12 OutlookGoogleCalendarSync.Exception [0] -  Code: 0x80131502,-2146233086; Location: ValidateDate() in <Unknown File>
> 2025-01-28 08:58:50,074 ERROR 12 OutlookGoogleCalendarSync.Exception [0] -     bei System.DateTimeOffset.ValidateDate(DateTime dateTime, TimeSpan offset)
>    bei System.DateTimeOffset..ctor(DateTime dateTime)
>    bei System.DateTimeOffset.op_Implicit(DateTime dateTime)
>    bei OutlookGoogleCalendarSync.Outlook.Calendar.UpdateCalendarEntry(AppointmentItem& ai, Event ev, Int32& itemModified, Boolean forceCompare)
>    bei OutlookGoogleCalendarSync.Outlook.Calendar.UpdateCalendarEntries(Dictionary`2 entriesToBeCompared, Int32& entriesUpdated)
> 2025-01-28 08:58:50,829 ERROR 12 OutlookGoogleCalendarSync.Console [0] -  29.01.2025 08:30 => "d0d76feb250a37d7beae4035c0be1f36"
> 2025-01-28 08:58:50,830 ERROR 12 OutlookGoogleCalendarSync.Console [0] -  Appointment update failed.
> 2025-01-28 08:58:50,830 ERROR 12 OutlookGoogleCalendarSync.Exception [0] -  System.ArgumentOutOfRangeException: Die nach dem Anwenden des Offsets dargestellte UTC-Zeit muss zwischen den Jahren 0 und 10000 liegen.
> Parametername: offset
> 2025-01-28 08:58:50,831 ERROR 12 OutlookGoogleCalendarSync.Exception [0] -  Code: 0x80131502,-2146233086; Location: ValidateDate() in <Unknown File>
> 2025-01-28 08:58:50,831 ERROR 12 OutlookGoogleCalendarSync.Exception [0] -     bei System.DateTimeOffset.ValidateDate(DateTime dateTime, TimeSpan offset)
>    bei System.DateTimeOffset..ctor(DateTime dateTime)
>    bei System.DateTimeOffset.op_Implicit(DateTime dateTime)
>    bei OutlookGoogleCalendarSync.Outlook.Calendar.UpdateCalendarEntry(AppointmentItem& ai, Event ev, Int32& itemModified, Boolean forceCompare)
>    bei OutlookGoogleCalendarSync.Outlook.Calendar.UpdateCalendarEntries(Dictionary`2 entriesToBeCompared, Int32& entriesUpdated)
> 2025-01-28 08:58:51,544 ERROR 12 OutlookGoogleCalendarSync.Console [0] -  29.01.2025 14:00 => "f603fc1e94f7a399aca7e2283ec821b1"
> 2025-01-28 08:58:51,545 ERROR 12 OutlookGoogleCalendarSync.Console [0] -  Appointment update failed.
> 2025-01-28 08:58:51,545 ERROR 12 OutlookGoogleCalendarSync.Exception [0] -  System.ArgumentOutOfRangeException: Die nach dem Anwenden des Offsets dargestellte UTC-Zeit muss zwischen den Jahren 0 und 10000 liegen.
> Parametername: offset
> 2025-01-28 08:58:51,545 ERROR 12 OutlookGoogleCalendarSync.Exception [0] -  Code: 0x80131502,-2146233086; Location: ValidateDate() in <Unknown File>
> 2025-01-28 08:58:51,545 ERROR 12 OutlookGoogleCalendarSync.Exception [0] -     bei System.DateTimeOffset.ValidateDate(DateTime dateTime, TimeSpan offset)
>    bei System.DateTimeOffset..ctor(DateTime dateTime)
>    bei System.DateTimeOffset.op_Implicit(DateTime dateTime)
>    bei OutlookGoogleCalendarSync.Outlook.Calendar.UpdateCalendarEntry(AppointmentItem& ai, Event ev, Int32& itemModified, Boolean forceCompare)
>    bei OutlookGoogleCalendarSync.Outlook.Calendar.UpdateCalendarEntries(Dictionary`2 entriesToBeCompared, Int32& entriesUpdated)
> 2025-01-28 08:58:52,352 ERROR 12 OutlookGoogleCalendarSync.Console [0] -  28.01.2025 13:00 => "2c8dfbafbef4ab25328e559ce7f9281b"
> 2025-01-28 08:58:52,353 ERROR 12 OutlookGoogleCalendarSync.Console [0] -  Appointment update failed.
> 2025-01-28 08:58:52,353 ERROR 12 OutlookGoogleCalendarSync.Exception [0] -  System.ArgumentOutOfRangeException: Die nach dem Anwenden des Offsets dargestellte UTC-Zeit muss zwischen den Jahren 0 und 10000 liegen.
> Parametername: offset
> 2025-01-28 08:58:52,354 ERROR 12 OutlookGoogleCalendarSync.Exception [0] -  Code: 0x80131502,-2146233086; Location: ValidateDate() in <Unknown File>
> 2025-01-28 08:58:52,354 ERROR 12 OutlookGoogleCalendarSync.Exception [0] -     bei System.DateTimeOffset.ValidateDate(DateTime dateTime, TimeSpan offset)
>    bei System.DateTimeOffset..ctor(DateTime dateTime)
>    bei System.DateTimeOffset.op_Implicit(DateTime dateTime)
>    bei OutlookGoogleCalendarSync.Outlook.Calendar.UpdateCalendarEntry(AppointmentItem& ai, Event ev, Int32& itemModified, Boolean forceCompare)
>    bei OutlookGoogleCalendarSync.Outlook.Calendar.UpdateCalendarEntries(Dictionary`2 entriesToBeCompared, Int32& entriesUpdated)
> ```  

 _Originally posted by @lemonbutter in [#1978](https://github.com/phw198/OutlookGoogleCalendarSync/issues/1978#issuecomment-2618168734)_

FYI @MortenAnd

**Comment by lestarte** [comment]
Hi. Maybe this is the same problem or is in connection - but my Outlook now suddenly since maybe two days has a time offset of 1 hour (negative) to the Google Calendar. I didn't change anything, but I remember that OGCS had an update, I think last week. May this have to do with the update and/or is correlating with the above mentioned problem? Or should I file a separate bug report for this? 
Thanks,
Olli

**Comment by d-treegardener** [comment]
@lestarte The offset was fixed with the hotfix 1 of the new version

**Comment by lestarte** [comment]
Oh, thanks! But I didn't get a notification about a new version. Will update manually. It was really annoying ;)
Have a nice day!

**Comment by Vasago** [comment]
Hello
Have the same issue and now everything is shifted 1 hour or even 2 hours early. The diff problem was solved as you mentioned in the previous ticket. But how to make it right now? See the picture Below can the time be taken directly from the meeting time and not from anywhere else? The original Time is from 13-17 but it is still syncing according to a different times for some reason even when I do the FULL SYNC option ...

![Image](https://github.com/user-attachments/assets/8bda5601-1009-45b8-ac13-e72a896deeb1)

**Comment by Vasago** [comment]
BTW with the version 2.11.2.3 the Outlook <-- Google syncing still removes 1 hour when doing sync or full sync ...

**Comment by Vasago** [comment]
Also this version is ignoring time frame and changing meetings in year 2020 even though I set 60 days in the past a 120 in the future

**Comment by MortenAnd** [comment]
Hi @phw198  Is it possible to download the version before these issues started.?

**Comment by d-treegardener** [comment]
@MortenAnd 
there you find all binaries: https://github.com/phw198/OutlookGoogleCalendarSync/releases

**Comment by phw198** [comment]
:package: The error encountered in the title of this issue, not any of the unrelated chatter about items syncing with hour offsets, should now be resolved with [hotfix v2.11.2.4.zip](https://github.com/user-attachments/files/18593699/v2.11.2.4.zip) (see [instructions for applying](https://github.com/phw198/OutlookGoogleCalendarSync/wiki/Reporting-Problems#applying-a-hotfix)).
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; [CRCs](https://github.com/phw198/OutlookGoogleCalendarSync/wiki/Known-Issues#cyclic-redundancy-checks---aka-crcs): Zip = `631BD9BD` Exe = `61B9045E`

Please let me know how it goes, @lemonbutter @MortenAnd

NB: This hotfix includes v2.11.2.1 from #2047

**Comment by d-treegardener** [comment]
@phw198 
Hi Paul, the fix worked. It finally could update my 5 events which threw these errors.
Thank you very much for the speedy fix :D very happe with the OutlookGoogleCalendarSync

**Comment by phw198** [comment]
Thanks for confirming @lemonbutter and for the donation :heart:

A pretty niche bug introduced by the update of Google APIs, which then affected users in a time zone ahead of GMT who were two-way syncing and previously synced items in Google were being recreated outside of OGCS. TBH, it seems like the other tool you are using is a little badly behaved in how it manages data on existing items - but we got to a solution, so no longer a problem!

@Vasago Please create a new issue and provide your logfile if you are still experiencing items syncing with the wrong start time.

**Comment by MortenAnd** [comment]
Thanks, seems to do the trick.

Sync works again.

⁣Mvh 
Morten Andresen​

Den 30. jan. 2025, 16.41, fra 16.41, Paul Woolcock ***@***.***> skrev:

**Comment by lestarte** [comment]
Still having these issues, some appointments are shifted 1 hour minus :/
My timezone is Germany/Berlin.

Luckily I wasn't _missing_ appointments but only got in an hour too early and wondered where all others may be ;)
Newest alpha is installed. No newer version found manually or via update.

**Comment by phw198** [comment]
@lestarte You have to apply the [v2.11.2.4 hotfix above](https://github.com/phw198/OutlookGoogleCalendarSync/issues/2055#issuecomment-2622777248) manually - running v2.11.2.0 has the issue which is being resolved.

**Comment by lestarte** [comment]
Ah okay, thank you. Totally oversaw the ZIP and didn't find any other place with infos about hotfixes. Wondered, but thought, they were pushed out normally as an alpha or beta. Thanks!
Have a great weekend!
