### ISSUE TITLE
When Appointment is modified in Outlook there are now 2 Appointments in Google

### ISSUE THREAD

**Issue by Bonagano** [phw198/OutlookGoogleCalendarSync#314]
Hello,

Let's say I create an appointment in Outlook scheduled for 10-11. Google sync goes according to plan. Then if I change the appointment in Outlook to 10-12. Google keeps the original 10-11 event and adds a new 10-12 event.

**Comment by phw198** [comment]
Which version of OGCS are you running? Upgraded to v2.6.0?

**Comment by Bonagano** [comment]
Yes.

**Comment by Bonagano** [comment]
And Outlook 2013

**Comment by Bonagano** [comment]
After doing some more tests it seems like the issue only affects appointments that I had created prior to updating to v2.6.0. New appointments seem to be behaving as they should.

**Comment by phw198** [comment]
:spiral_notepad: Please provide your OGcalsync.log file which covers the problem you are reporting [[see instructions](https://github.com/phw198/OutlookGoogleCalendarSync/wiki/Reporting-problems#posting-your-ogcalsynclog-file)].

**Comment by Bonagano** [comment]
Does this work?

https://gist.github.com/Bonagano/151932e866388977f20863929f1b1dbf

**Comment by Bonagano** [comment]
![outlook](https://user-images.githubusercontent.com/31451465/29840157-fd6e987a-8cce-11e7-8553-e9f0f007ea44.png)
![google](https://user-images.githubusercontent.com/31451465/29840156-fd6a59fe-8cce-11e7-97ad-cd7b34479ca7.png)

**Comment by phw198** [comment]
Please could you upgrade to v2.6.1 of OGCS, by ticking the `Check for alphas` box on the `About` page.

:package: Then apply [hotfix v2.6.1.1.zip](https://github.com/phw198/OutlookGoogleCalendarSync/files/1262059/v2.6.1.1.zip) [[see instructions for applying](https://github.com/phw198/OutlookGoogleCalendarSync/wiki/Reporting-Problems#applying-a-hotfix)].

Please let me know how it goes.

**Comment by Bonagano** [comment]
Hi Paul. I updated and applied the hotfix, but the issue remains.

**Comment by phw198** [comment]
Could you post your logfile again?

**Comment by Bonagano** [comment]
https://gist.github.com/Bonagano/3aae835da2d0ecdaf17c731571bbb227

**Comment by phw198** [comment]
What appears to be happening is that the wrong events are being matched between Outlook and Google. So when you move an appontment in Outlook, it's actually taking an event in Google from a completely different day and [changing the date and time](https://gist.github.com/Bonagano/3aae835da2d0ecdaf17c731571bbb227#file-gistfile1-txt-L1262-L1265) to match the moved appointment!

I'll need your help to get to the bottom of this. 
1. In OGCS under `Settings > Application Behaviour`, check the `Create CSVs` option.
1. Move an appointment in Outlook and perform a sync.
1. In Windows Explorer under `%APPDATA%\Outlook Google Calendar Sync`, you'll find
   1. `outlook_appointments.csv` - locate the appointment you moved in Outlook
   1. `google_events.csv` - locate the 2 "duplicated" events in Google. To locate the one that's been moved from a different date, you may need to look in the `OGcalsync.log` file to see where it came from, as the CSV will be a capture from _before_ the move.

If you can then let me have those 3 records, it should help me work out what's going on.

Thanks

**Comment by Bonagano** [comment]
There appear to only be 3 entries in my google_events.csv, should I be looking in one of the other google csv's?

https://gist.github.com/Bonagano/4d3e6d25fe4409886f9705126467f82e

**Comment by phw198** [comment]
Hmm, OK that's not quite worked as I'd hoped, but at least it provided the IDs of the Outlook item.

:package: Change of tack - [v2.6.1.3.zip](https://github.com/phw198/OutlookGoogleCalendarSync/files/1273289/v2.6.1.3.zip) now has extra custom logging to report the IDs I need when the Google item is moved. Could you [apply the hotfix](https://github.com/phw198/OutlookGoogleCalendarSync/wiki/Reporting-Problems#applying-a-hotfix), reproduce the issue and then reupload your logfile?

**Comment by Bonagano** [comment]
I tried applying the hotfix, but when I try to run the new OutlookGoogleCalendarSync.exe nothing happens?

There is no app-2.6.1.3-alpha folder. Should there be or does that get created when the program runs?

**Comment by Bonagano** [comment]
![calendar folder](https://user-images.githubusercontent.com/31451465/30064986-76904382-9221-11e7-9c38-5e47c64f809a.png)

**Comment by phw198** [comment]
Did you follow the "apply the hotfix" link in my previous post and follow the instructions?

**Comment by Bonagano** [comment]
Looks like a put it in the wrong folder. It's running now, will have the log file shortly

**Comment by Bonagano** [comment]
I moved the 9/1/17 appointment to 9/2/17, which left the original appointment behind. I can be more specific if you need it.

https://gist.github.com/Bonagano/de3c0da3aaad55a4b0f9f410a36a3f78

**Comment by phw198** [comment]
Really sorry @Bonagano, I [messed up the logging](https://gist.github.com/Bonagano/de3c0da3aaad55a4b0f9f410a36a3f78#file-gistfile1-txt-L2070-L2075) - can you try again with [v2.6.1.6.zip](https://github.com/phw198/OutlookGoogleCalendarSync/files/1278788/v2.6.1.6.zip)?

**Comment by Bonagano** [comment]
Ok, I did the same thing (after reverting the calendar back to how it was originally), moved the 9/1/17 appointment to 9/2/17, which left the original appointment behind.

https://gist.github.com/Bonagano/c8b9b2b658d3ce7ddd9f623be64ca9a3

**Comment by phw198** [comment]
OK, the good news is the [IDs against the two events are the same](https://gist.github.com/Bonagano/c8b9b2b658d3ce7ddd9f623be64ca9a3#file-gistfile1-txt-L952-L962), so the matching it working as expected. 

The bad news is I have no idea why the Google item on 4-Aug called "Edit Health Courses / Check & Connect" is being matched and updated to the Outlook item called "Edit Check & Connect" and moved from the 1-Sep to the 2-Sep. 

Do you have any idea why? Might you have copied one of these items to simplify creating the other at some point?

**Comment by Bonagano** [comment]
Yes I often copy and paste events in Outlook, but it's never been a problem before

**Comment by phw198** [comment]
OK, this looks like another symptom of the root cause for #224.

**Comment by phw198** [comment]
I've just posted a hotfix for #224, and am also posting it here so you can check if it resolves your issue too.

:package: [Hotfix-v2.6.1.8.zip](https://github.com/phw198/OutlookGoogleCalendarSync/files/1290941/v2.6.1.8.zip) - [see instructions for applying](https://github.com/phw198/OutlookGoogleCalendarSync/wiki/Reporting-Problems#applying-a-hotfix).

Let me know how it goes.

**Comment by Bonagano** [comment]
It appears the issue still persists with the 2.6.1.8 update. I'm also now getting this error occasionally "Updated Google event failed to save. Continue with synchronisation?"

**Comment by Bonagano** [comment]
When did the copying and pasting become an issue? I don't remember it before, but maybe I never noticed. I also checked the #224 thread, what is "Shift+Sync"?

**Comment by phw198** [comment]
Can you provide the logfile? I think the issue might have come in around 2.4 where an issue was fixed related to an organiser rescheduling an appointment wouldn't sync properly - that behaviour is very similar to a copy.

Shift sync means holding the shift key when you click the `Sync` button.

**Comment by Bonagano** [comment]
And when should I use Shift Sync?

https://gist.github.com/Bonagano/f0a520d7c38f1c26d1a2979b53d75dfa

**Comment by phw198** [comment]
Shift-sync is for when ever you want to compare _all_ items in your calendar, not just the ones which have been modified since the last sync. I would suggest you try that, though I think the fix in v2.6.1.8 (and now v2.6.2) will only prevent the problem from occurring in the first place - it won't be able to fix items in Google that are incorrectly matching to Outlook items.

Seeing as you are only 1-way syncing, for any items that are "duplicate" I would delete them in Google (and the entire series if it's recurring), and then let OGCS recreate it properly. In fact, I think I would:
- Turn off Merge
- Turn on Confirm on Delete
- Shift-sync from Outlook to Google
- For any items that OGCS wants to delete
    - If it was created by syncing from Outlook, then allow the delete
    - If it existed in Google before you used OGCS, then decline the delete
- Turn back on Merge
- Turn off Confirm on Delete
- Resume standard syncing

**Comment by Bonagano** [comment]
The issue remains in v2.6.2, but it behaves differently. Here's what I did:
Made an appointment in Outlook named Test 2 on Monday 9/25 from 9am-5:30pm and copied it to 9/26 for the same time, then click sync. Sync appears to work as desired.
Next, I copy the Monday Test 2 appointment again and paste it to Friday 9/29, then click sync. OGCS places the copy on Monday, not on Friday. Now there are two Monday appointments, 1 Tuesday, but no Friday.

So it looks like an appointment can only be copied for one sync. If you paste after a sync has occurred it just makes a duplicate?

Log:
https://gist.github.com/Bonagano/bfcc60f6f22f7d3a1e45e8a36a7e2f0c

**Comment by Bonagano** [comment]
Any update on this?

**Comment by phw198** [comment]
Seems that the mechanism to find the copied item(s) isn't quite watertight. 

:package: Could you try some further testing with Hotfix [v2.6.2.3.zip](https://github.com/phw198/OutlookGoogleCalendarSync/files/1346648/v2.6.2.3.zip) which has some extra logging. [[See instructions for applying hotfix](https://github.com/phw198/OutlookGoogleCalendarSync/wiki/Reporting-Problems#applying-a-hotfix)].

Please let me know how it goes.

**Comment by phw198** [comment]
Any update on v2.6.2.3 @Bonagano?

**Comment by Bonagano** [comment]
After installing the hotfix, the About section tells me it's running 2.6.2.2 and not 2.6.2.3.

I tried recreating the issue with this version anyway and wan't able to. Everything appears to be behaving correctly!
