### ISSUE TITLE
Remove dependency on Google+ APIs

### ISSUE THREAD

**Issue by ronisaacson** [phw198/OutlookGoogleCalendarSync#646]
According to [this notice from Google](https://developers.google.com/+/api-shutdown), the Google+ APIs will be disappearing shortly. OGCS currently has a dependency on the "plus.people.get" API which needs to be removed.

**Comment by phw198** [comment]
Thanks for the heads up on this @ronisaacson, I think I might have missed the notification email from Google!

Looks like 
`https://www.googleapis.com/plus/v1/people/me?fields=emails`  
needs to change to 
`https://www.googleapis.com/oauth2/v2/userinfo?fields=email`

**Comment by phw198** [comment]
Issue #599 is currently blocking the next beta release, so may need to backport this fix to at least v2.7.5

**Comment by phw198** [comment]
It would be nice to notify users, but I don't have a mechanism for doing that through the app (maybe something I need to build in for future), only through website, Twitter and, um, Google+.

It's also worse than a simple upgrade as GitHub broke the in-app upgrade mechanism when removing TLS1.1 support - so people will have to upgrade manually. Will definitely have to knock up a doc to cover all this...

**Comment by ronisaacson** [comment]
Sorry to be the bearer of bad news! Let me know if you need any help.

**Comment by aawinther** [comment]
has the issue described been fixed?
 
Dear G Suite Administrator,
We are writing to follow-up on our email from December 10th 2018 PT, regarding a technical issue caused by a software update which affected Google+ APIs between November 7th, 2018 PT and November 13th, 2018 PT. During this time period, third party applications to which a user granted access may have had access to more Google user profile data than intended. We have determined that impact was limited to Google+ APIs that return profile information. This resulted in two potential issues:
1.	Apps that requested permission to view user profile information, such as their name, email address, occupation, age were granted permission to view profile information about that user, even when it was set to not-public.
2.	Apps with access to a user's profile information also had access to profile information that had been shared with the app user, including profile fields that were not shared publicly.
In both cases, this data was limited to profile fields. The bug did not give developers access to information such as financial data, national identification numbers, passwords, or similar data typically used for fraud or identity theft.
In our prior communication, we alerted you that some of your users may have been impacted by this issue. After further analysis, we have identified 1 of the users in your domain(s) experienced the issue. We are attaching the list of impacted users, the apps that had unintended access (if available), and corresponding affected fields.
Please note that this issue was referenced in the Google+ blog post dated December 10th, 2018.
We appreciate your business and sincerely apologize for any inconvenience this may have caused. If you have any questions, please contact Google Support and reference issue number 120744624.
Sincerely,
The G Suite Team

**Comment by aawinther** [comment]
Thank you Very Much!!

Cheers

Aage

 

Fra: Ron Isaacson [mailto:notifications@github.com] 
Sendt: 3. januar 2019 15:28
Til: phw198/OutlookGoogleCalendarSync
Cc: aawinther; Mention
Emne: Re: [phw198/OutlookGoogleCalendarSync] Remove dependency on Google+ APIs (#646)

 

@aawinther <https://github.com/aawinther> , this is really a Google issue. Google is telling you that it may have allowed access to your personal data without your authorization, by way of an insecure Google+ API. This specific notice tells you that Google revealed your e-mail address to OGCS, even though you might not have given approval for that to be shared.

In your case, there is no problem, as @phw198 <https://github.com/phw198>  (the developer of OGCS) has previously said that he doesn't store e-mail addresses and none of your information was compromised as a result of using OGCS. However, after dealing with several privacy-related issues, Google decided to shut down Google+ entirely (more info here <https://www.blog.google/technology/safety-security/project-strobe/> ). This includes eliminating access to the Google+ API that OGCS uses to set up access to your calendar. As a result, OGCS will need to switch to a different API.

Paul has made the change but not yet released a new version of OGCS. Once the new version is released, all OGCS users will need to upgrade or risk losing the ability to synchronize.

**Comment by samintz** [comment]
I received an email from Google today saying I was using an API that would be taken down in the next few days.  It's the OAuth token I use for OGCS.  I see by this thread that the issue is fixed and will be in the next release.  I am running Alpha 2.7.7.0.  When will the next release be available?

**Comment by samintz** [comment]
I cloned the repo and built it locally with the above fix.

**Comment by phw198** [comment]
I'll look to get a hotfix out within the next day.

@mrmascari If you can authenticate and get the list of calendars, I'm not sure you are hitting the Google+ issue. If you can post your `OGcalsync.log` file, or at least the end of it when you hit the error, I can confirm...

**Comment by mrmascari** [comment]
It's been running about half way through, and then generating an error:  You are not properly authenticated to Google

For a few weeks now.  Normally, disconnecting and reconnecting solves the problem.  At least until I close OGCS and open it again.  Then, it'll happen once and be good for a bunch of days afterwards.  Starting today, doing that doesn't solve the problem.

It's definitely an assumption that it's related to Google+, but the way they describe the intermittent and then more often failures felt like this was probably the issue.  I wasn't worried about it and just assumed it's related and would go away once the next version comes out.

Looking in the Google API dashboard, I can see I've generated traffic to plus.people.get today.  I see errors on the graph too, but can't download the CSV for them for some reason.

If it's not related, I can move this to it's own issue, instead of confusing this one.  :)

[OGcalsyncEdited.log](https://github.com/phw198/OutlookGoogleCalendarSync/files/2833187/OGcalsyncEdited.log)

**Comment by phw198** [comment]
@mrmascari Hmm, if this is related to Google+ then it's rather odd, as it is erroring when the call is using only the Calendar API:
```
2019-02-05 12:08:27,765 DEBUG  8 OutlookGoogleCalendarSync.GoogleOgcs.Calendar [0] -  Retrieving all events from Google: 11/20/2018 -> 11/21/2018
2019-02-05 12:08:27,819 WARN  8 OutlookGoogleCalendarSync.GoogleOgcs.Calendar [0] -  Google.Apis.Requests.RequestError
Daily Limit for Unauthenticated Use Exceeded. Continued use requires signup. [403]
Errors [
	Message[Daily Limit for Unauthenticated Use Exceeded. Continued use requires signup.] Location[ - ] Reason[dailyLimitExceededUnreg] Domain[usageLimits]
]

2019-02-05 12:08:27,820 ERROR  8 OutlookGoogleCalendarSync.Console [0] -  You are not properly authenticated to Google.
```
Someone on StackOverflow mentioned that logging in from multiple locations can cause this error - do you have OGCS running eg at home and work simultaneously? Another post talks about increasing the number of "queries per 100 seconds" quota limit (though I'd be surprised if you're hitting this on your own keys).

Let's see if the hotfix resolves it before worrying too much, though.

**Comment by mrmascari** [comment]
Just on 1 computer and I only use this credential for this application.  I sync an entire year, about 450 items with a bunch that have the root for a recurring prior to the window.  I suppose it's possible that's generating a lot of requests as they're found.

My theory is that it's some type of back end interaction between the being sunset plus authentication and then the validity of that credential later on when used to access calendar, causing it to fail in a strange way someplace where it shouldn't normally fail since the credential was good earlier.

But, I haven't read the code.  :)

If it doesn't go away after the plus fix is released, I'll open a new issue.

PS:  Thanks for all the work.  I'm sure this solves a personal itch and it's very appreciated that you're willing to share that solution with us.


Edit before posting:  I found the "queries per 100 seconds" setting and changed it from 500 to 900.  Running a fresh sync, the graph shows a peak of 92 on a 1 minute average.

Also, the sync worked.  Either the limit change was it, or it's just the intermittent plus support as they turn it off.  I had to disconnect and reconnect too.  :)


Thanks again.

**Comment by phw198** [comment]
:package: [Hotfix v2.7.7.14.zip](https://github.com/phw198/OutlookGoogleCalendarSync/files/2834913/v2.7.7.14.zip) available ([see instructions for applying](https://github.com/phw198/OutlookGoogleCalendarSync/wiki/Reporting-Problems#applying-a-hotfix)).

This is just the API change applied to v2.7.7.0.
