### ISSUE TITLE
Continual Retry to Delete Recurring All Day Events

### ISSUE THREAD

**Issue by phw198** [phw198/OutlookGoogleCalendarSync#77]
Deleting 12 Google calendar entries...  
Not deleted: 2/17/2010 (R) =&gt; "John ------'s Birthday"  
Not deleted: 9/14/2003 (R) =&gt; "Dan ------'s Birthday"  
Not deleted: 10/2/2007 (R) =&gt; "Kathy ------'s Birthday"  
Not deleted: 1/17/2012 (R) =&gt; "James ------'s Birthday"  
Not deleted: 11/1/2011 (R) =&gt; "David -----'s Birthday"  
and so forth...  
  
I have Outlook Sync set to ask me when it deletes an event. There are 12
recurring events (examples detailed above) that Sync keeps trying to delete.
So I have to manually hit "No" each time.  

Work Item Details
--------------------
**Original CodePlex Issue:**	[Issue 497](http://outlookgooglecalendarsync.codeplex.com/workitem/497)
**Status:**	Proposed
**Reason Closed:**	Unassigned
**Assigned to:**	Unassigned
**Reported on:**	Apr 17 at 11:05 PM
**Reported by:**	MobileTom
**Updated on:**	Wed at 4:50 PM
**Updated by:**	dlmcmurr

#### Plaintext Attachments

[CodePlex Issue #497 Plain Text Attachments](https://gist.github.com/ea5336427e41b65305c5b4b222c5397b)

**Comment by phw198** [comment]
On *2017-05-10 23:03:00 UTC*, **dlmcmurr** commented:

I've got the same issue after upgrading to 2.4.0.0, except my recurring calendar entries are 0 minutes rather than all day. I have 52 of them. The old version worked great for me.

**Comment by phw198** [comment]
On *2017-05-10 23:50:07 UTC*, **dlmcmurr** commented:

Here's the error text from OGcalsync.log: Found Google item missing Outlook IDs., on each of the 52 items.

**Comment by nereusuj** [comment]
I have got the same issue. I had no choice but rollback to 2.3.0.0

**Comment by matt-thommo** [comment]
I have the same issue. After upgrading I had a number of recurring (annual) events that requested confirmation for deletion.
I have the sync date range set to +/- 365 days. It is only recurring events with the first occurrence outside this range and there is one occurrence inside this date range where it tries to delete on sync.
I thought perhaps if I re-created the events it would resolve the issue. I confirmed deletion for all of these events and then re-created (some I re-created in Outlook, some in Google Calendar).
The first sync worked correctly (i.e. new events were pushed in both directions) but then subsequent syncs the events were tagged for deletion again.

It also seems that any changes made to these events either in Outlook or Google Calendar are not synchronised.

**Comment by phw198** [comment]
I think might be a feature of issue #82. 

Please could you try [Hotfix-v2.4.0.4.zip](https://github.com/phw198/OutlookGoogleCalendarSync/files/1029788/Hotfix-v2.4.0.4.zip) [[see instructions for applying](https://github.com/phw198/OutlookGoogleCalendarSync/wiki/Reporting-Problems#applying-a-hotfix)] and see if the problem persists (it'll need applying over v2.4). If it does, please upload your v2.4.0.4 logfile. Thanks!

**Comment by dlmcmurr** [comment]
Tried 2.4.0.4 and had same experience. Log attached: 
[OGcalsync.txt](https://github.com/phw198/OutlookGoogleCalendarSync/files/1037087/OGcalsync.txt)

**Comment by nereusuj** [comment]
I have the same with @dlmcmurr. I cannot upload logs in my office.

**Comment by phw198** [comment]
@dlmcmurr your issue looks different from the OP - their issue is from 2-way sync on items originating before the sync period. You're just syncing from O > G. Also, your G birthday items don't look like all day items as they all start at 8am?

Anyway, I notice you're excluding items in the "Holiday" category - these birthdays aren't in that category in Outlook are they?

**Comment by phw198** [comment]
@nereusuj [See instructions](https://github.com/phw198/OutlookGoogleCalendarSync/wiki/Reporting-problems#posting-your-ogcalsynclog-file) for uploading your log file

**Comment by dlmcmurr** [comment]
Paul,

No, they are not in the holiday category. I excluded them because the google calendar had its own holidays and I was getting many duplicates. Excluding mine was the quick solution. Mine were originating in 2011 and 2012, but I changed them all to originate within the last 365 days. I used the 8am time to avoid getting reminders at midnight. After modifying all the outlook entries to the last year and clearing the google calendar, it all worked the first time with no deletion questions. I then used the google web calendar to change the color of all the birthdays so they would stand out on my phone. The next sync had all the deletion questions. One person said his worked the first time then wouldn’t after that. I can’t say for sure if mine is like that or failed after I edited the color in google. If you want me to clear the google calendar again, I can schedule some time to do that if it would help. Are the unclaimed entries anything to worry about?

Really like your app if we can get it working properly again.

Thanks,
Dave

**Comment by nereusuj** [comment]
Please refer following logs.
https://gist.github.com/nereusuj/88dcddc7e5c40e0dc43b573563f7b42f

**Comment by phw198** [comment]
Thanks guys for the input - I think I may have found the bug.

📦 This should now be resolved with [Hotfix-v2.4.0.5.zip](https://github.com/phw198/OutlookGoogleCalendarSync/files/1040313/Hotfix-v2.4.0.5.zip) [[see instructions for applying](https://github.com/phw198/OutlookGoogleCalendarSync/wiki/Reporting-Problems#applying-a-hotfix)].

Please let me know how it goes. If there's still a problem, please bump up the logging level to FINE and resubmit your logs (but I hope this won't be necessary).

**Comment by nereusuj** [comment]
Bad news. ;-(
It fails with different errors.

```
CalendarSync.GoogleCalendar [0] - Retrieving specific Event with ID pkd7nc594j8js3rgr4cs6hnmho
2017-05-31 14:16:28,542 DEBUG 17 OutlookGoogleCalendarSync.GoogleCalendar [0] - Retrieving specific Event with ID agrusb74p7jbd4rbldpr59kcpc
2017-05-31 14:16:29,669 DEBUG 17 OutlookGoogleCalendarSync.GoogleCalendar [0] - Retrieving specific Event with ID s6qa2hnpjp1h0c5s19r21frs24
2017-05-31 14:16:30,907 INFO 17 OutlookGoogleCalendarSync.MainForm [0] - Failed to retrieve master for Google recurring event.
2017-05-31 14:16:31,119 INFO 17 OutlookGoogleCalendarSync.MainForm [0] - The following error was encountered during sync:-
2017-05-31 14:16:31,256 INFO 17 OutlookGoogleCalendarSync.MainForm [0] - 입력 문자열의 형식이 잘못되었습니다.
2017-05-31 14:16:31,256 ERROR 17 OutlookGoogleCalendarSync.OGCSexception [0] - System.FormatException: 입력 문자열의 형식이 잘못되었습니다.
2017-05-31 14:16:31,257 ERROR 17 OutlookGoogleCalendarSync.OGCSexception [0] - Code: 0x80131537;-2146233033
2017-05-31 14:16:31,257 ERROR 17 OutlookGoogleCalendarSync.OGCSexception [0] -    위치: OutlookGoogleCalendarSync.MainForm.synchronize()
   위치: OutlookGoogleCalendarSync.MainForm.<>c__DisplayClass2.<sync_Start>b__0(Object o, DoWorkEventArgs args)
```

The translated Korean message in log is "The input string is malformed"
Please find full logs here
https://gist.github.com/nereusuj/0469ace9fbced54514e5bc3e7c7f3486

**Comment by phw198** [comment]
📦 Sorry, my bad - I'm not really able to test these builds as I'm not on my usual development rig. Anyway, please try [Hotfix-v2.4.0.6.zip](https://github.com/phw198/OutlookGoogleCalendarSync/files/1040359/Hotfix-v2.4.0.6.zip) [[see instructions for applying](https://github.com/phw198/OutlookGoogleCalendarSync/wiki/Reporting-Problems#applying-a-hotfix)].

**Comment by nereusuj** [comment]
Thanks for quick patch.
But it is still failing with another error.

```
Total inc. recurring items spanning sync date range...
Failed to retrieve master for Google recurring event outside of sync range.
The following error was encountered during sync:-
값이 너무 크거나 작아 Int16 형식에 맞지 않습니다.
Operation aborted after 1 failed attempts!
```

The translated error message is
"The value is too large or too small to fit the Int16 format."

Full logs: https://gist.github.com/nereusuj/b1c6eb2ff76a40f20f8abfc46b4dc613

**Comment by phw198** [comment]
:flushed: 

:package: [Hotfix-v2.4.0.7.zip](https://github.com/phw198/OutlookGoogleCalendarSync/files/1040386/Hotfix-v2.4.0.7.zip) [[see instructions for applying](https://github.com/phw198/OutlookGoogleCalendarSync/wiki/Reporting-Problems#applying-a-hotfix)].

**Comment by dlmcmurr** [comment]
[OGcalsync.txt](https://github.com/phw198/OutlookGoogleCalendarSync/files/1041380/OGcalsync.txt)
Paul,

Looked like this 2.4.0.7 fixed my issue. Only asked to delete one and it was valid. Logs are attached. Thanks for all the good work!

 Dave

**Comment by nereusuj** [comment]
@phw198 It is resoved with your latest hotfix. thanks.

But I have another issue with timezone changing.
Timezone in my Outlook is Asia/Seoul but synced timezone in Google is Asia/Chita.
#223

**Comment by matt-thommo** [comment]
Thank you Paul.

Hotfix applied and it appears to have resolved the issue.

- matt

**Comment by phw198** [comment]
Thanks for confirming! I think that opens the way for the [next release](https://github.com/phw198/OutlookGoogleCalendarSync/projects/1).
