### ISSUE TITLE
Appointment update failed. Object reference not set to an instance of an object.

### ISSUE THREAD

**Issue by pmunin** [phw198/OutlookGoogleCalendarSync#849]
**OGCS Version**: v2.8.0.0
**Installed or Portable**: Installed
Outlook: 2016

Outlook ← Google
```
0 Outlook calendar entries to be deleted.
0 Outlook calendar entries to be created.
4 calendar entries to be compared.
Comparing 4 existing Outlook calendar entries

Appointment update failed.
Object reference not set to an instance of an object.
0 entries updated.
```

**Bug Description**  
I sync from Google To Outlook. (Outlook ← Google)

My Google account have access to another calendar but only in "See Busy/Free" mode. So all events in that calendar displayed with empty Title and empty Description.

When I sync that calendar (empty titles and descriptions) to Outlook for the First Time - everything is fine. However if in the parent calendar anything was updated in that event (time or title or description). Next sync will cause `Null reference exception`.

**Steps to Reproduce the Issue**  
1. Create Home Google Account with Home Calendar in it
2. Create Work Google Account
3. Share Home Calendar with Work Google Account with "See Busy/Free only" permissions
4. Configure Synchronization to outlook from Work Google Account - selecting Home Calendar.
5. Create event in Home Google Account/Home calendar - put any description
6. Synchronize and make sure event is imported to outlook with Empty Title and Description - sync should complete successfully
7. Change anything in Home Google Account/Home Calendar (title or time or description)
8. Sync again, and you will see error:
```
Appointment update failed.
Object reference not set to an instance of an object.
```

**Comment by pmunin** [comment]
Here is copy-paste from the log file:

```
2019-09-22 21:41:25,294 DEBUG  8 OutlookGoogleCalendarSync.OutlookOgcs.Calendar [0] -  Processing >> 9/23/2019 12:15 PM => ""
2019-09-22 21:41:25,312 FINE  8 OutlookGoogleCalendarSync.Sync.Engine [0] -  Comparing Start Timezone
2019-09-22 21:41:25,312 ULTRA-FINE  8 OutlookGoogleCalendarSync.Sync.Engine [0] -  Google  attribute: Eastern Standard Time
2019-09-22 21:41:25,313 ULTRA-FINE  8 OutlookGoogleCalendarSync.Sync.Engine [0] -  Outlook attribute: Eastern Standard Time
2019-09-22 21:41:25,313 FINE  8 OutlookGoogleCalendarSync.Sync.Engine [0] -  Comparing End Timezone
2019-09-22 21:41:25,313 ULTRA-FINE  8 OutlookGoogleCalendarSync.Sync.Engine [0] -  Google  attribute: Eastern Standard Time
2019-09-22 21:41:25,313 ULTRA-FINE  8 OutlookGoogleCalendarSync.Sync.Engine [0] -  Outlook attribute: Eastern Standard Time
2019-09-22 21:41:25,314 FINE  8 OutlookGoogleCalendarSync.Sync.Engine [0] -  Comparing Start time
2019-09-22 21:41:25,314 ULTRA-FINE  8 OutlookGoogleCalendarSync.Sync.Engine [0] -  Google  attribute: 9/23/2019 12:15:00 PM
2019-09-22 21:41:25,314 ULTRA-FINE  8 OutlookGoogleCalendarSync.Sync.Engine [0] -  Outlook attribute: 9/23/2019 12:15:00 PM
2019-09-22 21:41:25,315 FINE  8 OutlookGoogleCalendarSync.Sync.Engine [0] -  Comparing End time
2019-09-22 21:41:25,315 ULTRA-FINE  8 OutlookGoogleCalendarSync.Sync.Engine [0] -  Google  attribute: 9/23/2019 12:45:00 PM
2019-09-22 21:41:25,315 ULTRA-FINE  8 OutlookGoogleCalendarSync.Sync.Engine [0] -  Outlook attribute: 9/23/2019 12:45:00 PM
2019-09-22 21:41:25,320 FINE  8 OutlookGoogleCalendarSync.Sync.Engine [0] -  Comparing Subject
2019-09-22 21:41:25,321 ULTRA-FINE  8 OutlookGoogleCalendarSync.Sync.Engine [0] -  Google  attribute: 
2019-09-22 21:41:25,321 ULTRA-FINE  8 OutlookGoogleCalendarSync.Sync.Engine [0] -  Outlook attribute: 
2019-09-22 21:41:25,321 FINE  8 OutlookGoogleCalendarSync.Sync.Engine [0] -  Comparing Description
2019-09-22 21:41:25,322 ULTRA-FINE  8 OutlookGoogleCalendarSync.Sync.Engine [0] -  Google  attribute: 
2019-09-22 21:41:25,322 ULTRA-FINE  8 OutlookGoogleCalendarSync.Sync.Engine [0] -  Outlook attribute: 
2019-09-22 21:41:25,322 FINE  8 OutlookGoogleCalendarSync.Sync.Engine [0] -  Comparing Location
2019-09-22 21:41:25,322 ULTRA-FINE  8 OutlookGoogleCalendarSync.Sync.Engine [0] -  Google  attribute: 
2019-09-22 21:41:25,323 ULTRA-FINE  8 OutlookGoogleCalendarSync.Sync.Engine [0] -  Outlook attribute: 
2019-09-22 21:41:25,324 FINE  8 OutlookGoogleCalendarSync.Sync.Engine [0] -  Comparing Privacy
2019-09-22 21:41:25,324 ULTRA-FINE  8 OutlookGoogleCalendarSync.Sync.Engine [0] -  Google  attribute: olPrivate
2019-09-22 21:41:25,325 ULTRA-FINE  8 OutlookGoogleCalendarSync.Sync.Engine [0] -  Outlook attribute: olPrivate
2019-09-22 21:41:25,326 FINE  8 OutlookGoogleCalendarSync.Sync.Engine [0] -  Comparing Free/Busy
2019-09-22 21:41:25,326 ULTRA-FINE  8 OutlookGoogleCalendarSync.Sync.Engine [0] -  Google  attribute: olBusy
2019-09-22 21:41:25,326 ULTRA-FINE  8 OutlookGoogleCalendarSync.Sync.Engine [0] -  Outlook attribute: olBusy
2019-09-22 21:41:25,327 ERROR  8 OutlookGoogleCalendarSync.Console [0] -  Appointment update failed.
2019-09-22 21:41:25,394 ERROR  8 OutlookGoogleCalendarSync.Console [0] -  Object reference not set to an instance of an object.
2019-09-22 21:41:25,441 ULTRA-FINE  1 OutlookGoogleCalendarSync.Console [0] -  Console navigating.
2019-09-22 21:41:25,441 ERROR  8 OutlookGoogleCalendarSync.OGCSexception [0] -  System.NullReferenceException: Object reference not set to an instance of an object.
2019-09-22 21:41:25,442 ERROR  8 OutlookGoogleCalendarSync.OGCSexception [0] -  Code: 0x80004003;-2147467261
2019-09-22 21:41:25,443 ERROR  8 OutlookGoogleCalendarSync.OGCSexception [0] -     at OutlookGoogleCalendarSync.OutlookOgcs.Calendar.UpdateCalendarEntry(AppointmentItem& ai, Event ev, Int32& itemModified, Boolean forceCompare)
   at OutlookGoogleCalendarSync.OutlookOgcs.Calendar.UpdateCalendarEntries(Dictionary`2 entriesToBeCompared, Int32& entriesUpdated)
2019-09-22 21:41:25,449 ULTRA-FINE  1 OutlookGoogleCalendarSync.Console [0] -  Navigated status = Loading
2019-09-22 21:41:25,455 ULTRA-FINE  1 OutlookGoogleCalendarSync.Console [0] -  Console finished navigating
2019-09-22 21:41:25,463 ULTRA-FINE  1 OutlookGoogleCalendarSync.Console [0] -  Document completed.
2019-09-22 21:41:27,217 INFO  8 OutlookGoogleCalendarSync.Console [0] -  0 entries updated.

```

**Comment by phw198** [comment]
:arrow_double_up: Please upgrade to ![latest release](https://img.shields.io/github/release/phw198/OutlookGoogleCalendarSync/all.svg) by going to the `About` tab in OGCS, ticking the `Check for Alpha releases` box and then clicking `Check for Update`. 

v2.8.1 has some extra features around syncing a read-only calendar - can you see if it behaves any differently?

**Comment by phw198** [comment]
Scratch that, I've been able to replicate the issue on v2.8.1 too.

**Comment by pmunin** [comment]
Just updated app to Alpha 2.8.2 - the bug is still there

**Comment by verysonglaa** [comment]
Same here, did anybody find a workaround?

**Comment by pmunin** [comment]
@verysonglaa what I do is 
1) go to logs to find out by start date time which events in outlook caused exception (usually it's events that were updated in google cal)
2) delete those events in outlook
3) sync. While syncing those events are recreated in outlook.

It is very annoying to do every time an event in updated in google, but that's the only way i know.

**Comment by phw198** [comment]
:package: Apologies for the delay in getting to this, but it should now be resolved with [v2.8.3.16.zip](https://github.com/phw198/OutlookGoogleCalendarSync/files/4776260/v2.8.3.16.zip) ([see instructions for applying](https://github.com/phw198/OutlookGoogleCalendarSync/wiki/Reporting-Problems#applying-a-hotfix)).

Please let me know how it goes.

**Comment by kwagner115** [comment]
Paul,

Is your development strategy that these "hotfixes" are individually targeted code updates, or as in this example, Hot fix #16 is cumulative of all hotfixes to that point?

**Comment by phw198** [comment]
@kwagner115 No, not cumulative (unless necessary); they're built on top of the latest alpha release, eg 2.8.3.0, which is what the issues should be reported against (though I accepted this issue against 2.8.0 as I knew it wasn't fixed or affected by subsequent releases).

**Comment by kwagner115** [comment]
Thx Paul!
 
Keep up the great work…..
 
Kevin

**Comment by verysonglaa** [comment]
@phw198 Unfortunately I still have the same error with v2.8.3.16 (see log below)
 ```
at OutlookGoogleCalendarSync.GoogleOgcs.Calendar.UpdateCalendarEntries(Dictionary`2 entriesToBeCompared, Int32& entriesUpdated)
2020-06-15 09:57:29,575 DEBUG  17 OutlookGoogleCalendarSync.GoogleOgcs.Calendar [0] -  Processing >> 15.04.2020 09:30 (R) => "Weekly xxxxxx"
2020-06-15 09:57:29,577 DEBUG  17 OutlookGoogleCalendarSync.Recurrence [0] -  Creating Google iCalendar definition for recurring event.
2020-06-15 09:57:29,598 DEBUG  17 OutlookGoogleCalendarSync.Recurrence [0] -  RRULE:FREQ=WEEKLY
2020-06-15 09:57:29,652 DEBUG  17 OutlookGoogleCalendarSync.Recurrence [0] -  15.04.2020 09:30 (R) => "Weekly xxxxxx"
2020-06-15 09:57:29,653 DEBUG  17 OutlookGoogleCalendarSync.Recurrence [0] -  This is a recurring appointment with 6 exceptions that will now be iteratively compared.
2020-06-15 09:57:30,207 DEBUG  17 OutlookGoogleCalendarSync.GoogleOgcs.Calendar [0] -  Doing a dummy update in order to update the last modified date of recurring master event
2020-06-15 09:57:30,275 ERROR  17 OutlookGoogleCalendarSync.Console [0] -  Updated event failed to save.
2020-06-15 09:57:30,277 ERROR  17 OutlookGoogleCalendarSync.Console [0] -  Object reference not set to an instance of an object.
2020-06-15 09:57:30,284 ERROR  17 OutlookGoogleCalendarSync.OGCSexception [0] -  System.NullReferenceException: Object reference not set to an instance of an object.
2020-06-15 09:57:30,286 ERROR  17 OutlookGoogleCalendarSync.OGCSexception [0] -  Code: 0x80004003;-2147467261
2020-06-15 09:57:30,288 ERROR  17 OutlookGoogleCalendarSync.OGCSexception [0] -     at OutlookGoogleCalendarSync.GoogleOgcs.Calendar.HandleAPIlimits(GoogleApiException ex, Event ev)
   at OutlookGoogleCalendarSync.GoogleOgcs.Calendar.UpdateCalendarEntry_save(Event& ev)
   at OutlookGoogleCalendarSync.GoogleOgcs.Calendar.UpdateCalendarEntries(Dictionary`2 entriesToBeCompared, Int32& entriesUpdated)
2020-06-15 09:57:31,185 INFO  17 OutlookGoogleCalendarSync.Sync.Engine [0] -  User chose not to continue sync.
```

let me know if I should try different options

**Comment by phw198** [comment]
@verysonglaa Your error actually looks like #958, if you want to try the fix posted there.

**Comment by phw198** [comment]
@pmunin Any update on testing v2.8.3.16?

**Comment by pmunin** [comment]
@phw198 sorry man, I'm currently on paternity leave till September, will test it right away once I come back to work

**Comment by phw198** [comment]
@pmunin Congrats! And no worries, I'll be rolling the hotfix into the next alpha now anyway, so if the issue should remain we can track under a new issue.

**Comment by pmunin** [comment]
@phw198 thanks Paul. Sounds good, thanks for your efforts!

**Comment by kwagner115** [comment]
Paul,
 
I may have caught you in the middle of sync’ing the new release. Got a notice that 2.8.4 update available. I clicked, and it failed. Then said go to website for download. I did, and only found 2.8.3.

Kevin

**Comment by kwagner115** [comment]
Kevin
 
kwagner115@gmail.com <mailto:kwagner115@gmail.com> 
319-382-4461 (mobile)

**Comment by kwagner115** [comment]
Paul,
 
I then tried to log onto GITHUB and found 2.8.4 p[posted there. I downloaded
and tried to install. Now I get this error message:
 


 
 
 
Kevin

**Comment by phw198** [comment]
@kwagner115  As always, you can't attach files or screenshot to email updates. Log on to GitHub to do that.

Also I don't think what you're posting about has any relevance to this closed issue - please open a new issue.

**Comment by Rosmaninho** [comment]
I am still having this issue every time an update occurs in version 2.8.6.0.

**Comment by phw198** [comment]
@Rosmaninho not sure what you mean by "an update". When an Outlook appointment is updated by OGCS? The error message in the subject of this issue is very generic and it's a rather old issue, so I doubt you do have exactly the same problem.

Please raise a new issue if necessary.
